-- NurseMate starter content for the local-data MVP & Philippine Nursing Reviewer.
-- Safe to rerun: content rows are upserted by stable IDs.

begin;

insert into public.subjects (id, name, description, icon, accent, sort_order)
values
  ('community-health-ph', 'Community Health Nursing (Philippines)', 'Public health nursing in the Philippines, Primary Health Care (LOI 949), 8 PHC elements, 4 A''s, BHW empowerment, and healthcare delivery levels.', 'Users', 'emerald', 5),
  ('fundamentals', 'Fundamentals of Nursing', 'Core bedside skills, safety habits, assessment basics, and the nursing process.', 'HeartPulse', 'pink', 10),
  ('anatomy-physiology', 'Anatomy and Physiology', 'Body systems, normal function, and clinically relevant relationships.', 'Activity', 'blue', 20),
  ('pharmacology', 'Pharmacology', 'Medication safety, classifications, dosage thinking, and nursing responsibilities.', 'Pill', 'purple', 30),
  ('medical-surgical', 'Medical-Surgical Nursing', 'Adult health conditions, priority assessment, and clinical decision-making.', 'Stethoscope', 'teal', 40),
  ('maternal-child', 'Maternal and Child Nursing', 'Pregnancy, newborn care, postpartum assessment, and family-centered teaching.', 'Baby', 'rose', 50),
  ('psychiatric', 'Psychiatric Nursing', 'Therapeutic communication, mental health assessment, crisis care, and safety.', 'Brain', 'amber', 60)
on conflict (id) do update
set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  accent = excluded.accent,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.topics (subject_id, id, name, description, starter_mastery, sort_order)
values
  ('community-health-ph', 'chn-ph-overview', 'Public Health Nursing Overview', 'Definitions by C.E. Winslow (3Ps), Araceli S. Maglaya, WHO, and 10 Essential Functions.', 70, 10),
  ('community-health-ph', 'phc-legal-elements', 'Primary Health Care & 8 Elements', 'LOI 949 legal basis, Alma Ata 1978, EPI, endemic disease control, and Generics Act (RA 6675).', 65, 20),
  ('community-health-ph', 'phc-principles', 'PHC Principles & Community Participation', '4 A''s, community participation as heart and soul, BHW roles, self-reliance, and devolution.', 75, 30),
  ('community-health-ph', 'levels-health-care', 'Philippine Health Care Delivery System', 'Primary (RHU/BHS), Secondary (District/Provincial), and Tertiary (PGH, PHC, POC, NCMH).', 68, 40),
  ('fundamentals', 'nursing-process', 'Nursing process', 'Assessment, diagnosis, planning, implementation, and evaluation.', 72, 10),
  ('fundamentals', 'vital-signs', 'Vital signs', 'Temperature, pulse, respirations, blood pressure, oxygen saturation, and pain.', 84, 20),
  ('fundamentals', 'infection-control', 'Infection control', 'Hand hygiene, PPE, transmission routes, and isolation basics.', 66, 30),
  ('fundamentals', 'patient-safety', 'Patient safety', 'Fall prevention, identification checks, safe environment, and reporting.', 78, 40),
  ('anatomy-physiology', 'cardiovascular-system', 'Cardiovascular system', 'Heart flow, perfusion, pulses, and common assessment clues.', 61, 10),
  ('anatomy-physiology', 'respiratory-system', 'Respiratory system', 'Ventilation, oxygenation, breath sounds, and gas exchange.', 69, 20),
  ('anatomy-physiology', 'renal-system', 'Renal system', 'Fluid balance, urine formation, electrolytes, and elimination.', 57, 30),
  ('pharmacology', 'drug-classifications', 'Drug classifications', 'Common medication groups and expected therapeutic effects.', 52, 10),
  ('pharmacology', 'dosage-calculations', 'Dosage calculations', 'Safe calculation habits and dose checks.', 48, 20),
  ('pharmacology', 'medication-safety', 'Medication safety', 'Rights of medication administration and high-alert precautions.', 64, 30),
  ('medical-surgical', 'cardiac-care', 'Cardiac care', 'Chest pain, heart failure basics, perfusion, and nursing priorities.', 55, 10),
  ('medical-surgical', 'respiratory-care', 'Respiratory care', 'Dyspnea, oxygen therapy basics, positioning, and assessment trends.', 63, 20),
  ('medical-surgical', 'gastrointestinal-care', 'Gastrointestinal care', 'Nutrition, elimination, abdominal assessment, and symptom patterns.', 70, 30),
  ('maternal-child', 'prenatal-care', 'Prenatal care', 'Routine teaching, warning signs, nutrition, and appointment flow.', 73, 10),
  ('maternal-child', 'labor-delivery', 'Labor and delivery', 'Labor stages, comfort measures, fetal monitoring basics, and priorities.', 59, 20),
  ('maternal-child', 'newborn-care', 'Newborn care', 'Thermoregulation, feeding basics, safety, and early assessment.', 76, 30),
  ('psychiatric', 'therapeutic-communication', 'Therapeutic communication', 'Listening, reflecting, open-ended questions, and trust-building responses.', 81, 10),
  ('psychiatric', 'anxiety', 'Anxiety', 'Assessment cues, safety, calming approaches, and escalation signs.', 68, 20),
  ('psychiatric', 'crisis-intervention', 'Crisis intervention', 'Immediate safety, support, de-escalation, and resource connection.', 58, 30)
on conflict (subject_id, id) do update
set
  name = excluded.name,
  description = excluded.description,
  starter_mastery = excluded.starter_mastery,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.flashcards (
  id,
  subject_id,
  topic_id,
  front,
  back,
  explanation,
  difficulty,
  tags,
  source,
  starter_due_label,
  starter_mastery
)
values
  (
    'fc-ph-1',
    'community-health-ph',
    'chn-ph-overview',
    'According to C.E. Winslow, what is the definition of Public Health (3Ps)?',
    'The art and science of Preventing disease, Prolonging life, and Promoting health through the organized efforts of society.',
    'C.E. Winslow''s classical definition emphasizes societal organization to prevent disease, prolong life, and promote physical/mental health and efficiency.',
    'easy',
    array['CHN', 'Public Health', 'Winslow 3Ps', 'Philippines'],
    'CHN Lesson 1 - Lady of Lourdes Hospital & Colleges / C.E. Winslow',
    'due_now',
    70
  ),
  (
    'fc-ph-2',
    'community-health-ph',
    'chn-ph-overview',
    'How did Araceli S. Maglaya define Community Health Nursing in the Philippines?',
    'The utilization of the nursing process in the different levels of clientele — individuals, families, population groups, and communities — concerned with the promotion of health, prevention of disease and disability, and rehabilitation.',
    'Maglaya''s landmark definition is a cornerstone in Philippine nursing education and the Philippine Nurse Licensure Examination (PNLE).',
    'medium',
    array['CHN', 'Maglaya', 'Nursing Process', 'PNLE'],
    'Maglaya, et al. - Nursing Practice in the Community (5th ed.)',
    'due_now',
    65
  ),
  (
    'fc-ph-3',
    'community-health-ph',
    'phc-legal-elements',
    'What is the legal basis of Primary Health Care (PHC) in the Philippines?',
    'Letter of Instruction (LOI) 949, signed on October 19, 1979 by President Ferdinand E. Marcos.',
    'LOI 949 mandated the then Ministry of Health (now DOH) to adopt Primary Health Care as an approach towards health development at the community level.',
    'easy',
    array['PHC', 'LOI 949', 'Legal Basis', 'Philippine Law'],
    'Letter of Instruction No. 949 (Oct 19, 1979) / DOH Philippines',
    'today',
    72
  ),
  (
    'fc-ph-4',
    'community-health-ph',
    'phc-principles',
    'What is considered the ''heart and soul'' of Primary Health Care?',
    'Community Participation.',
    'Without active involvement and empowerment of community members in decision-making and planning, primary health care cannot achieve sustained self-reliance.',
    'easy',
    array['PHC', 'Community Participation', 'Core Principles'],
    'CHN Lesson 1 - Principles and Strategies of PHC',
    'due_now',
    78
  ),
  (
    'fc-ph-5',
    'community-health-ph',
    'phc-principles',
    'What are the 4 A''s of health services under Primary Health Care?',
    'Accessibility, Availability, Affordability, and Acceptability (plus Appropriateness).',
    'Health services must be physically reachable (accessible), present when needed (available), economically feasible (affordable), culturally sound (acceptable), and suited to local needs (appropriate).',
    'medium',
    array['4 A''s', 'PHC Principles', 'CHN'],
    'CHN Lesson 1 - Principles of PHC',
    'tomorrow',
    60
  ),
  (
    'fc-ph-6',
    'community-health-ph',
    'phc-legal-elements',
    'What are the 8 Elements of Primary Health Care (ELEMENTS acronym)?',
    '1. Education for Health\n2. Locally Endemic Disease Control\n3. Expanded Program on Immunization (EPI)\n4. Maternal & Child Health and Family Planning\n5. Environmental Sanitation & Safe Water\n6. Nutrition & Food Supply\n7. Treatment of Communicable Diseases\n8. Supply of Essential Drugs',
    'These 8 core elements form the baseline of comprehensive public health programs delivered through rural health units and barangay health stations.',
    'medium',
    array['8 Elements', 'PHC', 'DOH', 'WHO'],
    'WHO Alma Ata 1978 & DOH Philippines',
    'due_now',
    58
  ),
  (
    'fc-ph-7',
    'community-health-ph',
    'phc-legal-elements',
    'Which Philippine law was enacted to support the supply of essential drugs in communities?',
    'The Generics Act of the Philippines (Republic Act No. 6675).',
    'RA 6675 promotes, requires, and ensures the production of adequate supply, distribution, use, and acceptance of drugs and medicines identified by their generic names.',
    'medium',
    array['RA 6675', 'Generics Act', 'Essential Drugs', 'Philippine Law'],
    'Republic Act No. 6675 / CHN Lesson 1',
    'today',
    64
  ),
  (
    'fc-ph-8',
    'community-health-ph',
    'levels-health-care',
    'Which health facilities belong to the Primary Level of health care delivery in the Philippines?',
    'Rural Health Units (RHU), Barangay Health Stations (BHS), Main Health Centers, Community Hospitals, and private/semi-private outpatient clinics.',
    'Primary level facilities are the first point of contact between community residents and the healthcare delivery system.',
    'easy',
    array['RHU', 'BHS', 'Primary Care', 'Health System'],
    'Philippine Department of Health Delivery System',
    'tomorrow',
    74
  ),
  (
    'fc-ph-9',
    'community-health-ph',
    'levels-health-care',
    'Which Philippine institutions provide Tertiary Level specialized healthcare?',
    'National medical centers and specialty hospitals such as Philippine General Hospital (PGH), Philippine Heart Center (PHC), Philippine Orthopedic Center (POC), and National Center for Mental Health (NCMH).',
    'Tertiary care handles highly complex cases, multi-disciplinary subspecialties, and advanced diagnostics/surgeries.',
    'medium',
    array['Tertiary Care', 'PGH', 'PHC', 'POC', 'NCMH'],
    'Philippine Health Care Delivery System / CHN Lesson 1',
    'later',
    67
  ),
  (
    'fc-ph-10',
    'community-health-ph',
    'phc-legal-elements',
    'Under the DOH Expanded Program on Immunization (EPI), at what age is the first Measles vaccine (MCV1) given?',
    'At 9 months of age (given subcutaneously in the upper outer arm).',
    'The DOH EPI schedule targets infants under 1 year for full immunization; MCV1 is given at 9 months and MCV2/MMR at 12-15 months.',
    'medium',
    array['EPI', 'Measles', 'Vaccination Schedule', 'DOH'],
    'DOH Expanded Program on Immunization Guidelines',
    'due_now',
    62
  ),
  (
    'fc-1',
    'fundamentals',
    'nursing-process',
    'What are the five steps of the nursing process?',
    'Assessment, diagnosis, planning, implementation, and evaluation.',
    'The process gives nursing care a structured clinical reasoning flow.',
    'easy',
    array['ADPIE', 'care planning'],
    'Common nursing education concept - verify with course materials.',
    'due_now',
    76
  ),
  (
    'fc-2',
    'fundamentals',
    'vital-signs',
    'Before documenting a blood pressure, what should the nurse confirm?',
    'That the cuff size, patient position, site, and reading context are appropriate.',
    'Technique affects accuracy, so context matters when interpreting trends.',
    'medium',
    array['assessment', 'blood pressure'],
    'Common nursing skills lab concept - verify with instructor guidance.',
    'today',
    63
  ),
  (
    'fc-3',
    'fundamentals',
    'infection-control',
    'What is the single most important routine action to reduce infection transmission?',
    'Performing hand hygiene at the correct moments.',
    'Hand hygiene interrupts transmission between patients, surfaces, and staff.',
    'easy',
    array['safety', 'PPE'],
    'Common infection prevention concept - verify with facility policy.',
    'due_now',
    69
  ),
  (
    'fc-4',
    'anatomy-physiology',
    'cardiovascular-system',
    'What does perfusion describe?',
    'The delivery of oxygenated blood to tissues.',
    'Nurses assess perfusion through mental status, skin signs, pulses, capillary refill, and vital sign trends.',
    'easy',
    array['perfusion', 'assessment'],
    'Common anatomy and nursing assessment concept - verify with textbook.',
    'tomorrow',
    71
  ),
  (
    'fc-5',
    'anatomy-physiology',
    'respiratory-system',
    'What is the main purpose of alveoli?',
    'Gas exchange between air and blood.',
    'Alveoli allow oxygen to enter the bloodstream and carbon dioxide to leave it.',
    'easy',
    array['oxygenation', 'gas exchange'],
    'Common anatomy concept - verify with textbook.',
    'today',
    74
  ),
  (
    'fc-6',
    'pharmacology',
    'medication-safety',
    'Why are two patient identifiers used before medication administration?',
    'To reduce the risk of giving a medication to the wrong patient.',
    'Identification checks are a core medication safety step and should follow facility policy.',
    'easy',
    array['medication rights', 'safety'],
    'Common medication safety concept - verify with facility policy.',
    'due_now',
    68
  ),
  (
    'fc-7',
    'pharmacology',
    'dosage-calculations',
    'What should a nurse do when a calculated medication dose seems unusual?',
    'Pause, recheck the calculation, verify the order, and follow policy before administering.',
    'Dose concerns should be resolved before medication reaches the patient.',
    'medium',
    array['dosage', 'safety'],
    'Common nursing safety concept - verify with instructor/facility policy.',
    'due_now',
    49
  ),
  (
    'fc-8',
    'medical-surgical',
    'cardiac-care',
    'Which broad symptom cluster can suggest reduced cardiac output?',
    'Fatigue, cool skin, weak pulses, dizziness, low urine output, or mental status changes.',
    'Trends and the whole assessment matter more than one isolated cue.',
    'medium',
    array['cardiac', 'priority cues'],
    'General med-surg nursing concept - verify with clinical references.',
    'today',
    54
  ),
  (
    'fc-9',
    'medical-surgical',
    'respiratory-care',
    'Which position is commonly used to ease breathing in a dyspneic patient?',
    'High Fowler''s position, if appropriate for the patient.',
    'Upright positioning can improve lung expansion while assessment and provider orders guide care.',
    'easy',
    array['dyspnea', 'positioning'],
    'Common respiratory nursing concept - verify with facility policy.',
    'later',
    82
  ),
  (
    'fc-10',
    'maternal-child',
    'newborn-care',
    'Why is newborn thermoregulation a nursing priority?',
    'Newborns can lose heat quickly and may use extra energy and oxygen to stay warm.',
    'Maintaining warmth supports stability after birth.',
    'medium',
    array['newborn', 'thermoregulation'],
    'Common maternal-child nursing concept - verify with textbook.',
    'tomorrow',
    66
  ),
  (
    'fc-11',
    'psychiatric',
    'therapeutic-communication',
    'What is the purpose of reflection in therapeutic communication?',
    'To encourage the patient to explore feelings or meaning in their own words.',
    'Reflection can show attention without taking control of the conversation.',
    'easy',
    array['communication', 'psych'],
    'Common psychiatric nursing concept - verify with instructor guidance.',
    'today',
    81
  ),
  (
    'fc-12',
    'psychiatric',
    'crisis-intervention',
    'What is the first nursing priority during a behavioral crisis?',
    'Immediate safety for the patient, staff, and others.',
    'Safety comes before deeper teaching or long-term planning.',
    'medium',
    array['safety', 'priority'],
    'Common crisis nursing concept - verify with facility policy.',
    'due_now',
    57
  )
on conflict (id) do update
set
  subject_id = excluded.subject_id,
  topic_id = excluded.topic_id,
  front = excluded.front,
  back = excluded.back,
  explanation = excluded.explanation,
  difficulty = excluded.difficulty,
  tags = excluded.tags,
  source = excluded.source,
  starter_due_label = excluded.starter_due_label,
  starter_mastery = excluded.starter_mastery,
  updated_at = now();

insert into public.questions (
  id,
  subject_id,
  topic_id,
  type,
  prompt,
  scenario_patient,
  scenario_vitals,
  scenario_assessment,
  explanation,
  difficulty,
  tags,
  source,
  accepted_answers
)
values
  (
    'q-ph-1',
    'community-health-ph',
    'phc-legal-elements',
    'multiple_choice',
    'On October 19, 1979, which presidential directive was signed by President Ferdinand E. Marcos serving as the legal basis of Primary Health Care in the Philippines?',
    null,
    array[]::text[],
    null,
    'LOI 949 signed on October 19, 1979 is the official legal basis of Primary Health Care (PHC) in the Philippines, instructing the health ministry to institutionalize PHC in communities.',
    'easy',
    array['PHC', 'LOI 949', 'Philippine Law', 'PNLE'],
    'CHN Lesson 1 - Lady of Lourdes Hospital & Colleges / DOH Philippines',
    array['Letter of Instruction (LOI) 949']
  ),
  (
    'q-ph-2',
    'community-health-ph',
    'chn-ph-overview',
    'multiple_choice',
    'According to renowned Filipino nursing author Araceli S. Maglaya, Community Health Nursing is defined as:',
    null,
    array[]::text[],
    null,
    'Araceli Maglaya defines CHN as utilizing the nursing process across four levels of clientele (individual, family, population groups, community) focused on health promotion, disease prevention, and rehabilitation.',
    'easy',
    array['CHN Definition', 'Maglaya', 'PNLE'],
    'Maglaya, et al. - Nursing Practice in the Community (5th ed.)',
    array['The utilization of the nursing process in different levels of clientele (individuals, families, population groups, communities) for health promotion, disease prevention, and rehabilitation']
  ),
  (
    'q-ph-3',
    'community-health-ph',
    'phc-principles',
    'true_false',
    'Community participation is widely recognized as the ''heart and soul'' of Primary Health Care.',
    null,
    array[]::text[],
    null,
    'Primary health care relies on community participation as its heart and soul, empowering local residents and Barangay Health Workers (BHWs) to lead health initiatives.',
    'easy',
    array['PHC Principles', 'Community Participation'],
    'CHN Lesson 1 - Principles and Strategies of PHC',
    array['True']
  ),
  (
    'q-ph-4',
    'community-health-ph',
    'levels-health-care',
    'true_false',
    'In the Philippine health care delivery system, a Barangay Health Station (BHS) is categorized under the Tertiary Level of care.',
    null,
    array[]::text[],
    null,
    'A Barangay Health Station (BHS) and Rural Health Unit (RHU) belong to the Primary Level of health care delivery, not Tertiary.',
    'easy',
    array['Levels of Care', 'BHS', 'RHU'],
    'Philippine DOH Health Care Delivery Structure',
    array['False']
  ),
  (
    'q-ph-5',
    'community-health-ph',
    'phc-legal-elements',
    'select_all_that_apply',
    'Which of the following are among the 8 Elements of Primary Health Care (PHC) in the Philippines? Select all that apply.',
    null,
    array[]::text[],
    null,
    'The 8 PHC elements are: Education, Locally endemic disease control, EPI, Maternal & Child Health/Family Planning, Environmental Sanitation, Nutrition/Food Supply, Treatment of Communicable Diseases, and Supply of Essential Drugs.',
    'medium',
    array['8 Elements', 'PHC', 'DOH'],
    'WHO Alma Ata & DOH Philippines',
    array['Education for Health', 'Expanded Program on Immunization (EPI)', 'Locally Endemic Disease Control (e.g. Malaria, Schistosomiasis)', 'Supply of Essential Drugs']
  ),
  (
    'q-ph-6',
    'community-health-ph',
    'levels-health-care',
    'select_all_that_apply',
    'Which of the following Philippine hospitals represent the Tertiary Level of specialized healthcare? Select all that apply.',
    null,
    array[]::text[],
    null,
    'PGH, PHC, NCMH, and POC are national tertiary specialized medical centers that provide subspecialty care, complex surgeries, and national referral services.',
    'medium',
    array['Tertiary Hospitals', 'PGH', 'PHC', 'POC', 'NCMH'],
    'CHN Lesson 1 - Levels of Prevention and Health Facilities',
    array['Philippine General Hospital (PGH)', 'Philippine Heart Center (PHC)', 'National Center for Mental Health (NCMH)', 'Philippine Orthopedic Center (POC)']
  ),
  (
    'q-ph-7',
    'community-health-ph',
    'phc-principles',
    'select_all_that_apply',
    'What are the 4 A''s of health services that guide Primary Health Care delivery? Select all that apply.',
    null,
    array[]::text[],
    null,
    'The 4 A''s of PHC ensure health services are physically accessible, continuously available, financially affordable, and culturally acceptable (and appropriate) to the community.',
    'medium',
    array['4 A''s', 'PHC Principles', 'CHN'],
    'CHN Lesson 1 - Principles of PHC',
    array['Accessibility', 'Availability', 'Affordability', 'Acceptability']
  ),
  (
    'q-ph-8',
    'community-health-ph',
    'phc-legal-elements',
    'identification',
    'Identify the Philippine Republic Act known as the Generics Act of the Philippines, enacted to ensure the supply and accessibility of essential drugs in communities (format: RA #### or Republic Act ####).',
    null,
    array[]::text[],
    null,
    'Republic Act No. 6675 (The Generics Act of 1988) mandates generic prescribing and labeling to promote accessible and affordable essential medicines.',
    'medium',
    array['RA 6675', 'Generics Act', 'Philippine Law'],
    'Republic Act 6675 / CHN Lesson 1',
    array['RA 6675', 'Republic Act 6675', 'RA6675']
  ),
  (
    'q-ph-9',
    'community-health-ph',
    'chn-ph-overview',
    'identification',
    'Identify the public health pioneer who defined public health with the 3Ps: ''preventing disease, prolonging life, and promoting health through organized community efforts''.',
    null,
    array[]::text[],
    null,
    'Charles-Edward Amory (C.E.) Winslow formulated this foundational definition of public health in 1920, emphasizing organized societal effort.',
    'easy',
    array['Winslow', '3Ps', 'Public Health'],
    'C.E. Winslow / CHN Lesson 1',
    array['C.E. Winslow', 'Winslow', 'CE Winslow']
  ),
  (
    'q-ph-10',
    'community-health-ph',
    'phc-principles',
    'prioritization',
    'A newly assigned Public Health Nurse in a Philippine Rural Health Unit (RHU) identifies high malnutrition rates in a remote barangay. According to PHC principles, which nursing action is the highest priority?',
    null,
    array[]::text[],
    null,
    'PHC emphasizes community self-reliance and people-centered development: starting from where the people are and building on what they have in partnership with local leaders and BHWs.',
    'hard',
    array['PHC Prioritization', 'Community Assembly', 'BHW'],
    'Principles and Strategies of PHC / Community Organization',
    array['Organize a community assembly with barangay leaders, BHWs, and mothers to assess local resources and formulate a community-managed feeding plan']
  ),
  (
    'q-ph-11',
    'community-health-ph',
    'phc-legal-elements',
    'patient_scenario',
    'According to the Philippine Department of Health (DOH) Expanded Program on Immunization (EPI) schedule, which vaccine should Nurse Maria prepare and administer today?',
    'Nurse Maria is conducting an Under-Five Well-Baby Clinic at the Barangay Health Station (BHS) in Caybiga. A mother presents her 9-month-old infant for routine immunization.',
    array['Temperature: 36.7°C', 'Weight: 8.4 kg (on target)', 'Alert and active'],
    'Review of the infant''s Child Health Card shows completed doses of BCG at birth, Hepatitis B, and 3 doses of Pentavalent/OPV/IPV. The infant has no contraindications.',
    'In the Philippine DOH EPI schedule, infants receive MCV1 (Measles Vaccine) at 9 months of age via subcutaneous injection to provide critical protection against measles.',
    'medium',
    array['EPI Schedule', 'Measles Vaccine', 'BHS', 'DOH'],
    'DOH Expanded Program on Immunization (EPI) Philippine Guidelines',
    array['Measles-Containing Vaccine 1 (MCV1 / Anti-Measles Vaccine) subcutaneously']
  ),
  (
    'q-ph-12',
    'community-health-ph',
    'phc-legal-elements',
    'patient_scenario',
    'Which initial diagnostic intervention should the Public Health Nurse prioritize at the primary care level?',
    'A 48-year-old tricycle driver visits the Rural Health Unit (RHU) reporting a 3-week history of productive cough, low-grade afternoon fever, nocturnal diaphoresis (night sweats), and 4 kg weight loss.',
    array['BP: 115/75 mmHg', 'Pulse: 80 bpm', 'Temp: 37.9°C', 'RR: 19/min'],
    'The patient resides in a crowded barangay. The RHU nurse recognizes symptoms indicative of Tuberculosis, a top communicable disease under the National TB Control Program (NTP).',
    'Under the DOH National Tuberculosis Control Program (NTP) at the RHU/PHC level, presumptive TB patients with cough >=2 weeks must undergo primary diagnostic sputum testing (DSSM/GeneXpert) to establish diagnosis and begin DOTS therapy.',
    'medium',
    array['Tuberculosis', 'DOTS', 'NTP', 'DOH', 'RHU'],
    'DOH National TB Control Program (NTP) / CHN Lesson 1',
    array['Collect sputum specimens for Direct Sputum Smear Microscopy (DSSM) / GeneXpert testing']
  ),
  (
    'q-1',
    'fundamentals',
    'nursing-process',
    'multiple_choice',
    'A student nurse gathers subjective and objective data before making a care plan. Which nursing process step is this?',
    null,
    array[]::text[],
    null,
    'Assessment is the data-gathering step that supports later nursing judgment.',
    'easy',
    array['ADPIE'],
    'Common nursing education concept - verify with course materials.',
    array['Assessment']
  ),
  (
    'q-2',
    'fundamentals',
    'infection-control',
    'true_false',
    'Gloves replace the need for hand hygiene when caring for a patient.',
    null,
    array[]::text[],
    null,
    'Hand hygiene is still required before and after glove use according to infection prevention principles.',
    'easy',
    array['infection control'],
    'Common infection prevention concept - verify with facility policy.',
    array['False']
  ),
  (
    'q-3',
    'fundamentals',
    'patient-safety',
    'select_all_that_apply',
    'Which actions support fall prevention for a patient at risk? Select all that apply.',
    null,
    array[]::text[],
    null,
    'Fall prevention focuses on access, clear pathways, appropriate footwear, and individualized safety planning.',
    'medium',
    array['safety', 'falls'],
    'Common patient safety concept - verify with facility policy.',
    array['Keep the call light within reach', 'Maintain a clutter-free pathway', 'Use non-skid footwear when appropriate']
  ),
  (
    'q-4',
    'anatomy-physiology',
    'respiratory-system',
    'multiple_choice',
    'Which structure is the primary site of gas exchange?',
    null,
    array[]::text[],
    null,
    'Alveoli are the tiny air sacs where oxygen and carbon dioxide exchange with capillaries.',
    'easy',
    array['respiratory'],
    'Common anatomy concept - verify with textbook.',
    array['Alveoli']
  ),
  (
    'q-5',
    'anatomy-physiology',
    'cardiovascular-system',
    'identification',
    'Identify the term for delivery of oxygenated blood to tissues.',
    null,
    array[]::text[],
    null,
    'Perfusion describes blood flow that delivers oxygen and nutrients to body tissues.',
    'easy',
    array['cardiovascular'],
    'Common anatomy and assessment concept - verify with textbook.',
    array['Perfusion']
  ),
  (
    'q-6',
    'pharmacology',
    'medication-safety',
    'multiple_choice',
    'A medication label does not match the medication administration record. What should the nurse do first?',
    null,
    array[]::text[],
    null,
    'Medication discrepancies must be resolved before administration.',
    'medium',
    array['medication safety'],
    'Common medication safety concept - verify with facility policy.',
    array['Pause and verify the order and medication']
  ),
  (
    'q-7',
    'pharmacology',
    'dosage-calculations',
    'true_false',
    'When unsure about a dosage calculation, it is safer to recheck and seek verification before giving the medication.',
    null,
    array[]::text[],
    null,
    'Dose questions should be resolved before administration to protect the patient.',
    'easy',
    array['dosage'],
    'Common nursing safety concept - verify with instructor/facility policy.',
    array['True']
  ),
  (
    'q-8',
    'medical-surgical',
    'respiratory-care',
    'patient_scenario',
    'Which nursing action is the best immediate priority?',
    'A 68-year-old patient reports shortness of breath after walking to the bathroom.',
    array['RR 26/min', 'SpO2 91% on room air', 'Pulse 104/min'],
    'The patient is sitting forward and speaking in short phrases.',
    'Breathing concerns call for prompt positioning and focused assessment while following orders and facility policy.',
    'medium',
    array['respiratory', 'priority'],
    'General med-surg nursing concept - verify with clinical references.',
    array['Assist the patient into a more upright position and continue focused assessment']
  ),
  (
    'q-9',
    'medical-surgical',
    'cardiac-care',
    'select_all_that_apply',
    'Which findings can be concerning for reduced perfusion? Select all that apply.',
    null,
    array[]::text[],
    null,
    'Reduced perfusion can affect mental status, skin signs, pulses, and urine output.',
    'medium',
    array['cardiac', 'perfusion'],
    'General med-surg nursing concept - verify with clinical references.',
    array['New confusion', 'Cool clammy skin', 'Low urine output']
  ),
  (
    'q-10',
    'maternal-child',
    'newborn-care',
    'multiple_choice',
    'Which action supports newborn temperature stability?',
    null,
    array[]::text[],
    null,
    'Drying and warmth help reduce heat loss after birth when appropriate for the newborn''s condition.',
    'easy',
    array['newborn'],
    'Common maternal-child nursing concept - verify with textbook.',
    array['Drying the newborn and using skin-to-skin when appropriate']
  ),
  (
    'q-11',
    'psychiatric',
    'therapeutic-communication',
    'multiple_choice',
    'Which response best reflects therapeutic communication?',
    null,
    array[]::text[],
    null,
    'Open-ended responses invite the patient to share more without dismissing their experience.',
    'easy',
    array['communication'],
    'Common psychiatric nursing concept - verify with instructor guidance.',
    array['Tell me more about what that has been like for you.']
  ),
  (
    'q-12',
    'psychiatric',
    'crisis-intervention',
    'prioritization',
    'A patient is escalating verbally in a crowded hallway. Which priority should guide the nurse''s first actions?',
    null,
    array[]::text[],
    null,
    'Immediate safety guides early crisis response before education or routine tasks.',
    'medium',
    array['crisis', 'priority'],
    'Common crisis nursing concept - verify with facility policy.',
    array['Safety']
  )
on conflict (id) do update
set
  subject_id = excluded.subject_id,
  topic_id = excluded.topic_id,
  type = excluded.type,
  prompt = excluded.prompt,
  scenario_patient = excluded.scenario_patient,
  scenario_vitals = excluded.scenario_vitals,
  scenario_assessment = excluded.scenario_assessment,
  explanation = excluded.explanation,
  difficulty = excluded.difficulty,
  tags = excluded.tags,
  source = excluded.source,
  accepted_answers = excluded.accepted_answers,
  updated_at = now();

insert into public.question_options (question_id, sort_order, option_text, is_correct)
values
  ('q-ph-1', 10, 'Letter of Instruction (LOI) 949', true),
  ('q-ph-1', 20, 'Republic Act 7160 (Local Government Code)', false),
  ('q-ph-1', 30, 'Republic Act 9173 (Philippine Nursing Act)', false),
  ('q-ph-1', 40, 'Presidential Decree 856 (Sanitation Code)', false),

  ('q-ph-2', 10, 'The utilization of the nursing process in different levels of clientele (individuals, families, population groups, communities) for health promotion, disease prevention, and rehabilitation', true),
  ('q-ph-2', 20, 'The administration of physician-prescribed medications exclusively in hospital ward settings', false),
  ('q-ph-2', 30, 'A specialized surgical nursing practice dedicated to operating room sterility and triage', false),
  ('q-ph-2', 40, 'The isolated provision of emergency trauma care in tertiary intensive care units', false),

  ('q-ph-3', 10, 'True', true),
  ('q-ph-3', 20, 'False', false),

  ('q-ph-4', 10, 'True', false),
  ('q-ph-4', 20, 'False', true),

  ('q-ph-5', 10, 'Education for Health', true),
  ('q-ph-5', 20, 'Expanded Program on Immunization (EPI)', true),
  ('q-ph-5', 30, 'Locally Endemic Disease Control (e.g. Malaria, Schistosomiasis)', true),
  ('q-ph-5', 40, 'Supply of Essential Drugs', true),
  ('q-ph-5', 50, 'Exclusive focus on cosmetic surgeries', false),

  ('q-ph-6', 10, 'Philippine General Hospital (PGH)', true),
  ('q-ph-6', 20, 'Philippine Heart Center (PHC)', true),
  ('q-ph-6', 30, 'National Center for Mental Health (NCMH)', true),
  ('q-ph-6', 40, 'Philippine Orthopedic Center (POC)', true),

  ('q-ph-7', 10, 'Accessibility', true),
  ('q-ph-7', 20, 'Availability', true),
  ('q-ph-7', 30, 'Affordability', true),
  ('q-ph-7', 40, 'Acceptability', true),

  ('q-ph-10', 10, 'Organize a community assembly with barangay leaders, BHWs, and mothers to assess local resources and formulate a community-managed feeding plan', true),
  ('q-ph-10', 20, 'Solicit donations of imported canned goods without consulting barangay officials', false),
  ('q-ph-10', 30, 'Instruct mothers to travel to a tertiary hospital in Metro Manila for dietary counseling', false),
  ('q-ph-10', 40, 'Reprimand families during home visits for improper cooking methods', false),

  ('q-ph-11', 10, 'Measles-Containing Vaccine 1 (MCV1 / Anti-Measles Vaccine) subcutaneously', true),
  ('q-ph-11', 20, 'Second BCG booster dose intradermally', false),
  ('q-ph-11', 30, 'Adult Tetanus Toxoid intramuscularly', false),
  ('q-ph-11', 40, 'Oral Polio Vaccine 4th extra dose only', false),

  ('q-ph-12', 10, 'Collect sputum specimens for Direct Sputum Smear Microscopy (DSSM) / GeneXpert testing', true),
  ('q-ph-12', 20, 'Immediately refer the patient to a tertiary orthopedic hospital without testing', false),
  ('q-ph-12', 30, 'Prescribe over-the-counter cough syrup and dismiss without follow-up', false),
  ('q-ph-12', 40, 'Order emergency thoracotomy surgery', false),

  ('q-1', 10, 'Assessment', true),
  ('q-1', 20, 'Planning', false),
  ('q-1', 30, 'Implementation', false),
  ('q-1', 40, 'Evaluation', false),
  ('q-2', 10, 'True', false),
  ('q-2', 20, 'False', true),
  ('q-3', 10, 'Keep the call light within reach', true),
  ('q-3', 20, 'Encourage unsafe independent ambulation', false),
  ('q-3', 30, 'Maintain a clutter-free pathway', true),
  ('q-3', 40, 'Use non-skid footwear when appropriate', true),
  ('q-4', 10, 'Alveoli', true),
  ('q-4', 20, 'Trachea', false),
  ('q-4', 30, 'Epiglottis', false),
  ('q-4', 40, 'Larynx', false),
  ('q-6', 10, 'Administer it because the patient is waiting', false),
  ('q-6', 20, 'Pause and verify the order and medication', true),
  ('q-6', 30, 'Ask a family member if it looks familiar', false),
  ('q-6', 40, 'Document the medication as refused', false),
  ('q-7', 10, 'True', true),
  ('q-7', 20, 'False', false),
  ('q-8', 10, 'Assist the patient into a more upright position and continue focused assessment', true),
  ('q-8', 20, 'Leave the room to document the finding', false),
  ('q-8', 30, 'Offer a full meal tray', false),
  ('q-8', 40, 'Delay assessment until the next scheduled vital signs', false),
  ('q-9', 10, 'New confusion', true),
  ('q-9', 20, 'Cool clammy skin', true),
  ('q-9', 30, 'Strong steady pulses', false),
  ('q-9', 40, 'Low urine output', true),
  ('q-10', 10, 'Drying the newborn and using skin-to-skin when appropriate', true),
  ('q-10', 20, 'Leaving wet linens in place', false),
  ('q-10', 30, 'Keeping the room cold', false),
  ('q-10', 40, 'Delaying assessment of temperature concerns', false),
  ('q-11', 10, 'Tell me more about what that has been like for you.', true),
  ('q-11', 20, 'You should not feel that way.', false),
  ('q-11', 30, 'Everything will be fine, so do not worry.', false),
  ('q-11', 40, 'I know exactly how you feel.', false),
  ('q-12', 10, 'Safety', true),
  ('q-12', 20, 'Long-term teaching', false),
  ('q-12', 30, 'Discharge paperwork', false),
  ('q-12', 40, 'Routine documentation', false)
on conflict (question_id, sort_order) do update
set
  option_text = excluded.option_text,
  is_correct = excluded.is_correct;

commit;
