import type { Flashcard, QuizQuestion, Subject } from "@/types/study";

export const subjects: Subject[] = [
  {
    id: "community-health-ph",
    name: "Community Health Nursing (Philippines)",
    description: "Public health nursing in the Philippines, Primary Health Care (LOI 949), 8 PHC elements, 4 A's, BHW empowerment, and healthcare delivery levels.",
    icon: "Users",
    accent: "emerald",
    topics: [
      {
        id: "chn-ph-overview",
        name: "Public Health Nursing Overview",
        description: "Definitions by C.E. Winslow (3Ps), Araceli S. Maglaya, WHO, and 10 Essential Functions.",
        mastery: 70,
      },
      {
        id: "phc-legal-elements",
        name: "Primary Health Care & 8 Elements",
        description: "LOI 949 legal basis, Alma Ata 1978, EPI, endemic disease control, and Generics Act (RA 6675).",
        mastery: 65,
      },
      {
        id: "phc-principles",
        name: "PHC Principles & Community Participation",
        description: "4 A's, community participation as heart and soul, BHW roles, self-reliance, and devolution.",
        mastery: 75,
      },
      {
        id: "levels-health-care",
        name: "Philippine Health Care Delivery System",
        description: "Primary (RHU/BHS), Secondary (District/Provincial), and Tertiary (PGH, PHC, POC, NCMH).",
        mastery: 68,
      },
    ],
  },
  {
    id: "fundamentals",
    name: "Fundamentals of Nursing",
    description: "Core bedside skills, safety habits, assessment basics, and the nursing process.",
    icon: "HeartPulse",
    accent: "pink",
    topics: [
      {
        id: "nursing-process",
        name: "Nursing process",
        description: "Assessment, diagnosis, planning, implementation, and evaluation (ADPIE).",
        mastery: 72,
      },
      {
        id: "vital-signs",
        name: "Vital signs",
        description: "Temperature, pulse, respirations, blood pressure, oxygen saturation, and pain.",
        mastery: 84,
      },
      {
        id: "infection-control",
        name: "Infection control",
        description: "Standard, Contact, Droplet, and Airborne precautions, PPE donning/doffing order.",
        mastery: 66,
      },
      {
        id: "patient-safety",
        name: "Patient safety",
        description: "Fall prevention, identification checks, RACE/PASS fire safety, and body mechanics.",
        mastery: 78,
      },
    ],
  },
  {
    id: "anatomy-physiology",
    name: "Anatomy and Physiology",
    description: "Body systems, normal function, and clinically relevant relationships.",
    icon: "Activity",
    accent: "blue",
    topics: [
      {
        id: "cardiovascular-system",
        name: "Cardiovascular system",
        description: "Cardiac conduction, SA node pacemaker, heart flow, perfusion, and pulses.",
        mastery: 61,
      },
      {
        id: "respiratory-system",
        name: "Respiratory system",
        description: "Alveoli gas exchange, ventilation, oxygenation, breath sounds, and V/Q.",
        mastery: 69,
      },
      {
        id: "renal-system",
        name: "Renal system",
        description: "Nephron filtration, RAAS, fluid balance, urine formation, and electrolytes.",
        mastery: 57,
      },
      {
        id: "nervous-system",
        name: "Nervous system",
        description: "Cranial nerves I-XII, central/peripheral nervous system, and Glasgow Coma Scale.",
        mastery: 64,
      },
    ],
  },
  {
    id: "pharmacology",
    name: "Pharmacology",
    description: "Medication safety, classifications, dosage thinking, and nursing responsibilities.",
    icon: "Pill",
    accent: "purple",
    topics: [
      {
        id: "drug-classifications",
        name: "Drug classifications",
        description: "Cardio, respiratory, antimicrobial, CNS, and endocrine drug groups.",
        mastery: 52,
      },
      {
        id: "dosage-calculations",
        name: "Dosage calculations",
        description: "D/H x V formula, IV drip rates (gtt/min), and weight-based calculations.",
        mastery: 48,
      },
      {
        id: "medication-safety",
        name: "Medication safety",
        description: "10 Rights of administration, High-Alert PINCH meds, and critical antidotes.",
        mastery: 64,
      },
    ],
  },
  {
    id: "medical-surgical",
    name: "Medical-Surgical Nursing",
    description: "Adult health conditions, priority assessment, and clinical decision-making.",
    icon: "Stethoscope",
    accent: "teal",
    topics: [
      {
        id: "cardiac-care",
        name: "Cardiac care",
        description: "Chest pain, MI MONA protocol, heart failure (left vs right), and perfusion cues.",
        mastery: 55,
      },
      {
        id: "respiratory-care",
        name: "Respiratory care",
        description: "Dyspnea, COPD hypoxic drive, asthma management, positioning, and oxygen therapy.",
        mastery: 63,
      },
      {
        id: "gastrointestinal-care",
        name: "Gastrointestinal care",
        description: "Appendicitis (McBurney's), GERD, cirrhosis/lactulose, and acute abdomen assessment.",
        mastery: 70,
      },
      {
        id: "endocrine-care",
        name: "Endocrine care",
        description: "Diabetes DKA vs HHS, thyroid disorders, and adrenal alterations.",
        mastery: 58,
      },
    ],
  },
  {
    id: "maternal-child",
    name: "Maternal and Child Nursing",
    description: "Pregnancy, newborn care, postpartum assessment, and family-centered teaching.",
    icon: "Baby",
    accent: "rose",
    topics: [
      {
        id: "prenatal-care",
        name: "Prenatal care",
        description: "Naegele's rule EDD, GTPAL obstetric history, fundal height, and warning signs.",
        mastery: 73,
      },
      {
        id: "labor-delivery",
        name: "Labor and delivery",
        description: "Stages of labor (1-4), true vs false labor, fetal monitoring, and comfort measures.",
        mastery: 59,
      },
      {
        id: "postpartum-care",
        name: "Postpartum care",
        description: "BUBBLE-HE assessment, lochia transitions, fundal massage, and PPH prevention.",
        mastery: 68,
      },
      {
        id: "newborn-care",
        name: "Newborn care",
        description: "APGAR scoring, thermoregulation, acrocyanosis, and newborn reflexes.",
        mastery: 76,
      },
    ],
  },
  {
    id: "psychiatric",
    name: "Psychiatric Nursing",
    description: "Therapeutic communication, mental health assessment, crisis care, and safety.",
    icon: "Brain",
    accent: "amber",
    topics: [
      {
        id: "therapeutic-communication",
        name: "Therapeutic communication",
        description: "Open-ended questions, reflection, clarifying, silence vs non-therapeutic traps.",
        mastery: 81,
      },
      {
        id: "anxiety",
        name: "Anxiety & Mood Disorders",
        description: "Mild to panic anxiety, depression, mania finger foods, and suicide precautions.",
        mastery: 68,
      },
      {
        id: "crisis-intervention",
        name: "Crisis intervention & Safety",
        description: "Immediate safety, de-escalation, hallucinations reality testing, and psychosis.",
        mastery: 58,
      },
      {
        id: "psychopharmacology",
        name: "Psychotropic medications",
        description: "Lithium therapeutic levels (0.6-1.2), SSRI serotonin syndrome, and NMS.",
        mastery: 62,
      },
    ],
  },
];

export const flashcards: Flashcard[] = [
  // Community Health Nursing (Philippines) Flashcards
  {
    id: "fc-ph-1",
    subjectId: "community-health-ph",
    topicId: "chn-ph-overview",
    front: "According to C.E. Winslow, what is the definition of Public Health (3Ps)?",
    back: "The art and science of Preventing disease, Prolonging life, and Promoting health through the organized efforts of society.",
    explanation: "C.E. Winslow's classical definition emphasizes societal organization to prevent disease, prolong life, and promote physical/mental health and efficiency.",
    difficulty: "Easy",
    tags: ["CHN", "Public Health", "Winslow 3Ps", "Philippines"],
    source: "CHN Lesson 1 - Lady of Lourdes Hospital & Colleges / C.E. Winslow",
    due: "Due now",
    mastery: 70,
  },
  {
    id: "fc-ph-2",
    subjectId: "community-health-ph",
    topicId: "chn-ph-overview",
    front: "How did Araceli S. Maglaya define Community Health Nursing in the Philippines?",
    back: "The utilization of the nursing process in the different levels of clientele — individuals, families, population groups, and communities — concerned with the promotion of health, prevention of disease and disability, and rehabilitation.",
    explanation: "Maglaya's landmark definition is a cornerstone in Philippine nursing education and the Philippine Nurse Licensure Examination (PNLE).",
    difficulty: "Medium",
    tags: ["CHN", "Maglaya", "Nursing Process", "PNLE"],
    source: "Maglaya, et al. - Nursing Practice in the Community (5th ed.)",
    due: "Due now",
    mastery: 65,
  },
  {
    id: "fc-ph-3",
    subjectId: "community-health-ph",
    topicId: "phc-legal-elements",
    front: "What is the legal basis of Primary Health Care (PHC) in the Philippines?",
    back: "Letter of Instruction (LOI) 949, signed on October 19, 1979 by President Ferdinand E. Marcos.",
    explanation: "LOI 949 mandated the then Ministry of Health (now DOH) to adopt Primary Health Care as an approach towards health development at the community level.",
    difficulty: "Easy",
    tags: ["PHC", "LOI 949", "Legal Basis", "Philippine Law"],
    source: "Letter of Instruction No. 949 (Oct 19, 1979) / DOH Philippines",
    due: "Today",
    mastery: 72,
  },
  {
    id: "fc-ph-4",
    subjectId: "community-health-ph",
    topicId: "phc-principles",
    front: "What is considered the 'heart and soul' of Primary Health Care?",
    back: "Community Participation.",
    explanation: "Without active involvement and empowerment of community members in decision-making and planning, primary health care cannot achieve sustained self-reliance.",
    difficulty: "Easy",
    tags: ["PHC", "Community Participation", "Core Principles"],
    source: "CHN Lesson 1 - Principles and Strategies of PHC",
    due: "Due now",
    mastery: 78,
  },
  {
    id: "fc-ph-5",
    subjectId: "community-health-ph",
    topicId: "phc-principles",
    front: "What are the 4 A's of health services under Primary Health Care?",
    back: "Accessibility, Availability, Affordability, and Acceptability (plus Appropriateness).",
    explanation: "Health services must be physically reachable (accessible), present when needed (available), economically feasible (affordable), culturally sound (acceptable), and suited to local needs (appropriate).",
    difficulty: "Medium",
    tags: ["4 A's", "PHC Principles", "CHN"],
    source: "CHN Lesson 1 - Principles of PHC",
    due: "Tomorrow",
    mastery: 60,
  },
  {
    id: "fc-ph-6",
    subjectId: "community-health-ph",
    topicId: "levels-health-care",
    front: "Which Philippine institutions provide Tertiary Level specialized healthcare?",
    back: "National medical centers and specialty hospitals such as Philippine General Hospital (PGH), Philippine Heart Center (PHC), Philippine Orthopedic Center (POC), and National Center for Mental Health (NCMH).",
    explanation: "Tertiary care handles highly complex cases, multi-disciplinary subspecialties, and advanced diagnostics/surgeries.",
    difficulty: "Medium",
    tags: ["Tertiary Care", "PGH", "PHC", "POC", "NCMH"],
    source: "Philippine Health Care Delivery System / CHN Lesson 1",
    due: "Later",
    mastery: 67,
  },

  // Fundamentals Flashcards
  {
    id: "fc-1",
    subjectId: "fundamentals",
    topicId: "nursing-process",
    front: "What are the five steps of the nursing process?",
    back: "Assessment, diagnosis, planning, implementation, and evaluation (ADPIE).",
    explanation: "The process gives nursing care a structured clinical reasoning flow.",
    difficulty: "Easy",
    tags: ["ADPIE", "care planning"],
    source: "Open RN Nursing Fundamentals (2nd ed. NCBI NBK610815)",
    due: "Due now",
    mastery: 76,
  },
  {
    id: "fc-2",
    subjectId: "fundamentals",
    topicId: "vital-signs",
    front: "What happens to a blood pressure reading if the cuff is too small/narrow for the patient's arm?",
    back: "The blood pressure reading will be falsely elevated (falsely high).",
    explanation: "A small cuff requires extra pressure to occlude the artery, resulting in an artificially high reading. A cuff that is too large causes a falsely low reading.",
    difficulty: "Medium",
    tags: ["assessment", "blood pressure", "vitals"],
    source: "Open RN Nursing Skills (2nd ed. NCBI NBK596735)",
    due: "Today",
    mastery: 63,
  },
  {
    id: "fc-3",
    subjectId: "fundamentals",
    topicId: "infection-control",
    front: "What is the proper sequence for donning PPE?",
    back: "1. Gown -> 2. Mask or Respirator -> 3. Goggles or Face Shield -> 4. Gloves.",
    explanation: "Gloves go on last so they can be pulled over the cuffs of the gown for complete skin protection.",
    difficulty: "Easy",
    tags: ["PPE", "Infection Control", "CDC"],
    source: "CDC Standard Precautions & Infection Control Guidelines",
    due: "Due now",
    mastery: 69,
  },
  {
    id: "fc-f-4",
    subjectId: "fundamentals",
    topicId: "patient-safety",
    front: "What does the fire safety acronym RACE stand for?",
    back: "Rescue patients in immediate danger -> Alarm (activate fire alarm) -> Contain (close doors/windows) -> Extinguish/Evacuate.",
    explanation: "RACE outlines the sequential priority actions when encountering a healthcare facility fire.",
    difficulty: "Easy",
    tags: ["Safety", "RACE", "Fire Safety"],
    source: "Hospital Safety Guidelines & Open RN",
    due: "Tomorrow",
    mastery: 80,
  },

  // Anatomy & Physiology Flashcards
  {
    id: "fc-4",
    subjectId: "anatomy-physiology",
    topicId: "cardiovascular-system",
    front: "What is the primary electrical pacemaker of the healthy human heart?",
    back: "The Sinoatrial (SA) Node, generating intrinsic impulses at 60–100 beats per minute.",
    explanation: "Located in the right atrium, the SA node initiates the normal cardiac conduction cycle.",
    difficulty: "Easy",
    tags: ["Cardiac Conduction", "SA Node", "A&P"],
    source: "OpenStax Anatomy and Physiology 2e",
    due: "Tomorrow",
    mastery: 71,
  },
  {
    id: "fc-5",
    subjectId: "anatomy-physiology",
    topicId: "respiratory-system",
    front: "What is the primary functional site of gas exchange in the human lungs?",
    back: "The Alveoli (alveolar-capillary membrane).",
    explanation: "Alveoli provide a large surface area with thin capillary walls for oxygen diffusion into blood and CO2 elimination.",
    difficulty: "Easy",
    tags: ["oxygenation", "gas exchange", "Alveoli"],
    source: "OpenStax Anatomy and Physiology 2e",
    due: "Today",
    mastery: 74,
  },
  {
    id: "fc-ap-3",
    subjectId: "anatomy-physiology",
    topicId: "renal-system",
    front: "What hormone is secreted by the kidneys in response to low oxygen levels to stimulate RBC production?",
    back: "Erythropoietin (EPO).",
    explanation: "Renal hypoxia stimulates EPO release, acting on bone marrow to accelerate erythropoiesis.",
    difficulty: "Medium",
    tags: ["Renal", "Erythropoietin", "Hematology"],
    source: "OpenStax Anatomy and Physiology 2e",
    due: "Due now",
    mastery: 59,
  },

  // Pharmacology Flashcards
  {
    id: "fc-6",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    front: "What is the specific antidote for acute Opioid overdose and respiratory depression?",
    back: "Naloxone (Narcan).",
    explanation: "Naloxone is an opioid antagonist that rapidly displaces opioids from receptor sites to restore ventilation.",
    difficulty: "Easy",
    tags: ["Antidote", "Naloxone", "Opioids", "Safety"],
    source: "Open RN Nursing Pharmacology (2nd ed. NCBI NBK595000)",
    due: "Due now",
    mastery: 85,
  },
  {
    id: "fc-7",
    subjectId: "pharmacology",
    topicId: "dosage-calculations",
    front: "What is the basic formula for calculating oral drug dosages?",
    back: "Dose Desired (D) ÷ Dose on Hand (H) × Quantity/Volume (V) = Amount to Administer.",
    explanation: "Always ensure units of measurement (mg, mcg, g) match before calculating.",
    difficulty: "Easy",
    tags: ["Dosage", "Math", "Calculations"],
    source: "Open RN Nursing Pharmacology (2nd ed.)",
    due: "Due now",
    mastery: 72,
  },
  {
    id: "fc-p-3",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    front: "What what what what antidote is administered for severe Heparin-induced anticoagulation/bleeding?",
    back: "Protamine Sulfate.",
    explanation: "Protamine sulfate forms a stable, inactive salt complex with heparin to neutralize its anticoagulant effect.",
    difficulty: "Medium",
    tags: ["Heparin", "Protamine Sulfate", "Antidote"],
    source: "Open RN Nursing Pharmacology (2nd ed.)",
    due: "Tomorrow",
    mastery: 68,
  },

  // Medical-Surgical Flashcards
  {
    id: "fc-8",
    subjectId: "medical-surgical",
    topicId: "cardiac-care",
    front: "What is the primary pathophysiological difference between Left-Sided and Right-Sided Heart Failure symptoms?",
    back: "Left-sided failure causes pulmonary congestion (dyspnea, crackles, orthopnea); Right-sided failure causes systemic venous congestion (JVD, peripheral edema, ascites, hepatomegaly).",
    explanation: "Left failure backs fluid into the lungs; Right failure backs fluid into systemic circulation.",
    difficulty: "Medium",
    tags: ["Heart Failure", "Cardiology", "Med-Surg"],
    source: "Open RN Health Alterations (NCBI NBK613078)",
    due: "Today",
    mastery: 66,
  },
  {
    id: "fc-9",
    subjectId: "medical-surgical",
    topicId: "respiratory-care",
    front: "Why is pursed-lip breathing beneficial for patients with COPD / Emphysema?",
    back: "It creates positive expiratory pressure in the airways, preventing alveolar collapse and prolonging exhalation to expel trapped CO2.",
    explanation: "Pursed-lip breathing reduces dyspnea and work of breathing in obstructive lung disease.",
    difficulty: "Easy",
    tags: ["COPD", "Pursed-Lip Breathing", "Respiratory"],
    source: "Open RN Health Alterations",
    due: "Later",
    mastery: 82,
  },

  // Maternal-Child Flashcards
  {
    id: "fc-10",
    subjectId: "maternal-child",
    topicId: "newborn-care",
    front: "What 5 parameters are assessed in the newborn APGAR scoring system?",
    back: "Appearance (color), Pulse (heart rate), Grimace (reflex irritability), Activity (muscle tone), and Respiration (respiratory effort).",
    explanation: "Scored at 1 and 5 minutes post-birth (scale 0-10) to evaluate transition to extrauterine life.",
    difficulty: "Easy",
    tags: ["APGAR", "Newborn", "Pediatrics"],
    source: "Open RN Nursing Health Promotion (NCBI NBK615319)",
    due: "Tomorrow",
    mastery: 84,
  },
  {
    id: "fc-mc-2",
    subjectId: "maternal-child",
    topicId: "prenatal-care",
    front: "What is Naegele's Rule for calculating the Estimated Date of Delivery (EDD)?",
    back: "First day of Last Menstrual Period (LMP) − 3 months + 7 days + 1 year.",
    explanation: "Assumes a standard 28-day menstrual cycle and conception on day 14.",
    difficulty: "Medium",
    tags: ["Naegele's Rule", "Obstetrics", "EDD"],
    source: "Open RN Nursing Health Promotion",
    due: "Today",
    mastery: 75,
  },

  // Psychiatric Nursing Flashcards
  {
    id: "fc-11",
    subjectId: "psychiatric",
    topicId: "therapeutic-communication",
    front: "Why should a nurse avoid asking 'Why' questions in therapeutic psychiatric communication?",
    back: "'Why' questions often sound accusatory, judgmental, or intimidating, making the patient defensive.",
    explanation: "Open-ended inquiries (e.g., 'What was happening when...') promote exploration without defensiveness.",
    difficulty: "Easy",
    tags: ["Communication", "Therapeutic", "Psych"],
    source: "Open RN Mental Health and Community Concepts (NCBI NBK616982)",
    due: "Today",
    mastery: 81,
  },
  {
    id: "fc-12",
    subjectId: "psychiatric",
    topicId: "psychopharmacology",
    front: "What is the narrow therapeutic serum level range for Lithium Carbonate in bipolar maintenance?",
    back: "0.6 to 1.2 mEq/L (Toxicity typically begins above 1.5 mEq/L).",
    explanation: "Signs of toxicity include coarse tremors, ataxia, vomiting, diarrhea, and confusion. Adequate hydration and steady sodium intake are vital.",
    difficulty: "Medium",
    tags: ["Lithium", "Therapeutic Range", "Bipolar", "Psychopharm"],
    source: "Open RN Mental Health and Community Concepts",
    due: "Due now",
    mastery: 62,
  },
];

export const quizQuestions: QuizQuestion[] = [
  // ==========================================
  // SUBJECT 1: Community Health Nursing (Philippines)
  // ==========================================
  {
    id: "q-ph-1",
    subjectId: "community-health-ph",
    topicId: "phc-legal-elements",
    type: "Multiple Choice",
    prompt: "On October 19, 1979, which presidential directive was signed by President Ferdinand E. Marcos serving as the legal basis of Primary Health Care in the Philippines?",
    options: [
      "Letter of Instruction (LOI) 949",
      "Republic Act 7160 (Local Government Code)",
      "Republic Act 9173 (Philippine Nursing Act)",
      "Presidential Decree 856 (Sanitation Code)",
    ],
    correctAnswer: "Letter of Instruction (LOI) 949",
    explanation: "LOI 949 signed on October 19, 1979 is the official legal basis of Primary Health Care (PHC) in the Philippines, instructing the health ministry to institutionalize PHC in communities.",
    difficulty: "Easy",
    tags: ["PHC", "LOI 949", "Philippine Law", "PNLE"],
    source: "CHN Lesson 1 - Lady of Lourdes Hospital & Colleges / DOH Philippines",
  },
  {
    id: "q-ph-2",
    subjectId: "community-health-ph",
    topicId: "chn-ph-overview",
    type: "Multiple Choice",
    prompt: "According to renowned Filipino nursing author Araceli S. Maglaya, Community Health Nursing is defined as:",
    options: [
      "The utilization of the nursing process in different levels of clientele (individuals, families, population groups, communities) for health promotion, disease prevention, and rehabilitation",
      "The administration of physician-prescribed medications exclusively in hospital ward settings",
      "A specialized surgical nursing practice dedicated to operating room sterility and triage",
      "The isolated provision of emergency trauma care in tertiary intensive care units",
    ],
    correctAnswer: "The utilization of the nursing process in different levels of clientele (individuals, families, population groups, communities) for health promotion, disease prevention, and rehabilitation",
    explanation: "Araceli Maglaya defines CHN as utilizing the nursing process across four levels of clientele (individual, family, population groups, community) focused on health promotion, disease prevention, and rehabilitation.",
    difficulty: "Easy",
    tags: ["CHN Definition", "Maglaya", "PNLE"],
    source: "Maglaya, et al. - Nursing Practice in the Community (5th ed.)",
  },
  {
    id: "q-ph-3",
    subjectId: "community-health-ph",
    topicId: "phc-principles",
    type: "True/False",
    prompt: "Community participation is widely recognized as the 'heart and soul' of Primary Health Care.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Primary health care relies on community participation as its heart and soul, empowering local residents and Barangay Health Workers (BHWs) to lead health initiatives.",
    difficulty: "Easy",
    tags: ["PHC Principles", "Community Participation"],
    source: "CHN Lesson 1 - Principles and Strategies of PHC",
  },
  {
    id: "q-ph-4",
    subjectId: "community-health-ph",
    topicId: "levels-health-care",
    type: "True/False",
    prompt: "In the Philippine health care delivery system, a Barangay Health Station (BHS) is categorized under the Tertiary Level of care.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "A Barangay Health Station (BHS) and Rural Health Unit (RHU) belong to the Primary Level of health care delivery, not Tertiary.",
    difficulty: "Easy",
    tags: ["Levels of Care", "BHS", "RHU"],
    source: "Philippine DOH Health Care Delivery Structure",
  },
  {
    id: "q-ph-5",
    subjectId: "community-health-ph",
    topicId: "phc-legal-elements",
    type: "Select All That Apply",
    prompt: "Which of the following are among the 8 Elements of Primary Health Care (PHC) in the Philippines? Select all that apply.",
    options: [
      "Education for Health",
      "Expanded Program on Immunization (EPI)",
      "Locally Endemic Disease Control (e.g. Malaria, Schistosomiasis)",
      "Supply of Essential Drugs",
      "Exclusive focus on cosmetic surgeries",
    ],
    correctAnswer: [
      "Education for Health",
      "Expanded Program on Immunization (EPI)",
      "Locally Endemic Disease Control (e.g. Malaria, Schistosomiasis)",
      "Supply of Essential Drugs",
    ],
    explanation: "The 8 PHC elements are: Education, Locally endemic disease control, EPI, Maternal & Child Health/Family Planning, Environmental Sanitation, Nutrition/Food Supply, Treatment of Communicable Diseases, and Supply of Essential Drugs.",
    difficulty: "Medium",
    tags: ["8 Elements", "PHC", "DOH"],
    source: "WHO Alma Ata & DOH Philippines",
  },
  {
    id: "q-ph-6",
    subjectId: "community-health-ph",
    topicId: "levels-health-care",
    type: "Select All That Apply",
    prompt: "Which of the following Philippine hospitals represent the Tertiary Level of specialized healthcare? Select all that apply.",
    options: [
      "Philippine General Hospital (PGH)",
      "Philippine Heart Center (PHC)",
      "National Center for Mental Health (NCMH)",
      "Philippine Orthopedic Center (POC)",
    ],
    correctAnswer: [
      "Philippine General Hospital (PGH)",
      "Philippine Heart Center (PHC)",
      "National Center for Mental Health (NCMH)",
      "Philippine Orthopedic Center (POC)",
    ],
    explanation: "PGH, PHC, NCMH, and POC are national tertiary specialized medical centers that provide subspecialty care, complex surgeries, and national referral services.",
    difficulty: "Medium",
    tags: ["Tertiary Hospitals", "PGH", "PHC", "POC", "NCMH"],
    source: "CHN Lesson 1 - Levels of Prevention and Health Facilities",
  },
  {
    id: "q-ph-7",
    subjectId: "community-health-ph",
    topicId: "phc-legal-elements",
    type: "Identification",
    prompt: "Identify the Philippine Republic Act known as the Generics Act of the Philippines, enacted to ensure the supply and accessibility of essential drugs in communities (format: RA #### or Republic Act ####).",
    options: [],
    correctAnswer: "RA 6675",
    explanation: "Republic Act No. 6675 (The Generics Act of 1988) mandates generic prescribing and labeling to promote accessible and affordable essential medicines.",
    difficulty: "Medium",
    tags: ["RA 6675", "Generics Act", "Philippine Law"],
    source: "Republic Act 6675 / CHN Lesson 1",
  },
  {
    id: "q-ph-8",
    subjectId: "community-health-ph",
    topicId: "phc-principles",
    type: "Prioritization",
    prompt: "A newly assigned Public Health Nurse in a Philippine Rural Health Unit (RHU) identifies high malnutrition rates in a remote barangay. According to PHC principles, which nursing action is the highest priority?",
    options: [
      "Organize a community assembly with barangay leaders, BHWs, and mothers to assess local resources and formulate a community-managed feeding plan",
      "Solicit donations of imported canned goods without consulting barangay officials",
      "Instruct mothers to travel to a tertiary hospital in Metro Manila for dietary counseling",
      "Reprimand families during home visits for improper cooking methods",
    ],
    correctAnswer: "Organize a community assembly with barangay leaders, BHWs, and mothers to assess local resources and formulate a community-managed feeding plan",
    explanation: "PHC emphasizes community self-reliance and people-centered development: starting from where the people are and building on what they have in partnership with local leaders and BHWs.",
    difficulty: "Hard",
    tags: ["PHC Prioritization", "Community Assembly", "BHW"],
    source: "Principles and Strategies of PHC / Community Organization",
  },
  {
    id: "q-ph-9",
    subjectId: "community-health-ph",
    topicId: "phc-legal-elements",
    type: "Patient Scenario",
    scenario: {
      patient: "Nurse Maria is conducting an Under-Five Well-Baby Clinic at the Barangay Health Station (BHS) in Caybiga. A mother presents her 9-month-old infant for routine immunization.",
      vitals: ["Temperature: 36.7°C", "Weight: 8.4 kg (on target)", "Alert and active"],
      assessment: "Review of the infant's Child Health Card shows completed doses of BCG at birth, Hepatitis B, and 3 doses of Pentavalent/OPV/IPV. The infant has no contraindications.",
    },
    prompt: "According to the Philippine Department of Health (DOH) Expanded Program on Immunization (EPI) schedule, which vaccine should Nurse Maria prepare and administer today?",
    options: [
      "Measles-Containing Vaccine 1 (MCV1 / Anti-Measles Vaccine) subcutaneously",
      "Second BCG booster dose intradermally",
      "Adult Tetanus Toxoid intramuscularly",
      "Oral Polio Vaccine 4th extra dose only",
    ],
    correctAnswer: "Measles-Containing Vaccine 1 (MCV1 / Anti-Measles Vaccine) subcutaneously",
    explanation: "In the Philippine DOH EPI schedule, infants receive MCV1 (Measles Vaccine) at 9 months of age via subcutaneous injection to provide critical protection against measles.",
    difficulty: "Medium",
    tags: ["EPI Schedule", "Measles Vaccine", "BHS", "DOH"],
    source: "DOH Expanded Program on Immunization (EPI) Philippine Guidelines",
  },

  // ==========================================
  // SUBJECT 2: Fundamentals of Nursing
  // ==========================================
  {
    id: "q-1",
    subjectId: "fundamentals",
    topicId: "nursing-process",
    type: "Multiple Choice",
    prompt: "A student nurse gathers subjective and objective data before making a care plan. Which nursing process step is this?",
    options: ["Assessment", "Planning", "Implementation", "Evaluation"],
    correctAnswer: "Assessment",
    explanation: "Assessment is the initial data-gathering step (ADPIE) that supports later clinical judgment.",
    difficulty: "Easy",
    tags: ["ADPIE"],
    source: "Open RN Nursing Fundamentals (2nd ed. NCBI NBK610815)",
  },
  {
    id: "q-2",
    subjectId: "fundamentals",
    topicId: "infection-control",
    type: "True/False",
    prompt: "Wearing clean non-sterile gloves eliminates the necessity of performing hand hygiene before and after patient contact.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Hand hygiene is still strictly required before donning gloves and immediately after glove removal to prevent cross-contamination.",
    difficulty: "Easy",
    tags: ["infection control", "WHO Hand Hygiene"],
    source: "CDC Standard Precautions & WHO Hand Hygiene Guidelines",
  },
  {
    id: "q-3",
    subjectId: "fundamentals",
    topicId: "patient-safety",
    type: "Select All That Apply",
    prompt: "Which nursing interventions directly reduce fall risk for an elderly hospitalized patient? Select all that apply.",
    options: [
      "Keep the call light within immediate reach",
      "Maintain a clear, clutter-free pathway to the bathroom",
      "Provide non-skid footwear during ambulation",
      "Keep the bed in the lowest position with wheels locked",
      "Raise all four bed side rails continuously without an order",
    ],
    correctAnswer: [
      "Keep the call light within immediate reach",
      "Maintain a clear, clutter-free pathway to the bathroom",
      "Provide non-skid footwear during ambulation",
      "Keep the bed in the lowest position with wheels locked",
    ],
    explanation: "Four raised side rails are considered a physical restraint in many jurisdictions and can increase fall injury if a patient attempts to climb over. Other choices are standard fall precautions.",
    difficulty: "Medium",
    tags: ["safety", "fall risk", "NCLEX"],
    source: "Open RN Nursing Fundamentals",
  },
  {
    id: "q-f-4",
    subjectId: "fundamentals",
    topicId: "infection-control",
    type: "Multiple Choice",
    prompt: "What is the correct sequence for donning personal protective equipment (PPE)?",
    options: [
      "Gown -> Mask/Respirator -> Goggles/Face Shield -> Gloves",
      "Gloves -> Gown -> Mask -> Goggles",
      "Mask -> Gown -> Gloves -> Goggles",
      "Goggles -> Mask -> Gloves -> Gown",
    ],
    correctAnswer: "Gown -> Mask/Respirator -> Goggles/Face Shield -> Gloves",
    explanation: "According to the CDC, PPE should be donned in the order of Gown, Mask or Respirator, Goggles or Face Shield, and finally Gloves extending over the gown cuffs.",
    difficulty: "Medium",
    tags: ["PPE", "CDC", "Infection Control"],
    source: "CDC Core Infection Prevention Practices",
  },
  {
    id: "q-f-5",
    subjectId: "fundamentals",
    topicId: "vital-signs",
    type: "Identification",
    prompt: "Identify the clinical concept frequently designated in nursing documentation as the '5th Vital Sign'.",
    options: [],
    correctAnswer: "Pain",
    explanation: "Pain is regarded as the 5th vital sign and should be assessed using standardized scales (e.g. numerical 0-10 or Wong-Baker faces).",
    difficulty: "Easy",
    tags: ["Vital Signs", "Pain Assessment"],
    source: "Open RN Nursing Skills (2nd ed.)",
  },
  {
    id: "q-f-6",
    subjectId: "fundamentals",
    topicId: "patient-safety",
    type: "Prioritization",
    prompt: "A nurse discovers a small fire in a trash can inside an occupied patient room. Following the RACE protocol, what is the nurse's first immediate action?",
    options: [
      "Rescue and remove the patient from immediate danger",
      "Activate the nearest fire alarm pull station",
      "Attempt to extinguish the fire with a fire extinguisher",
      "Close all room doors and windows",
    ],
    correctAnswer: "Rescue and remove the patient from immediate danger",
    explanation: "RACE begins with 'R' for Rescue: patient life and safety always precede alarm activation and fire containment.",
    difficulty: "Medium",
    tags: ["RACE", "Fire Safety", "Prioritization"],
    source: "Hospital Safety Standards & Open RN",
  },
  {
    id: "q-f-7",
    subjectId: "fundamentals",
    topicId: "vital-signs",
    type: "Patient Scenario",
    scenario: {
      patient: "A 72-year-old post-operative patient is receiving intravenous hydromorphone via PCA pump. On hourly rounds, the nurse observes slow, shallow breathing.",
      vitals: ["Respirations: 7 breaths/min", "SpO2: 86% on room air", "Pulse: 56 bpm", "Blood Pressure: 94/58 mmHg"],
      assessment: "The patient is difficult to arouse with verbal stimulation and responds only to painful stimuli with incomprehensible groans.",
    },
    prompt: "Which nursing intervention is the most critical priority?",
    options: [
      "Stimulate the patient, support ventilation with high-flow oxygen, and administer prescribed Naloxone (Narcan)",
      "Document the vital signs and re-evaluate in 30 minutes",
      "Increase the PCA lockout interval on the IV pump",
      "Offer the patient a warm oral beverage to stimulate wakefulness",
    ],
    correctAnswer: "Stimulate the patient, support ventilation with high-flow oxygen, and administer prescribed Naloxone (Narcan)",
    explanation: "Severe opioid-induced respiratory depression (RR < 8, hypoxia, unresponsiveness) is an emergency requiring immediate airway/ventilatory support and opioid reversal with Naloxone.",
    difficulty: "Hard",
    tags: ["Opioid Overdose", "Naloxone", "Respiratory Depression", "Priority"],
    source: "Open RN Nursing Fundamentals & Skills",
  },

  // ==========================================
  // SUBJECT 3: Anatomy and Physiology
  // ==========================================
  {
    id: "q-4",
    subjectId: "anatomy-physiology",
    topicId: "respiratory-system",
    type: "Multiple Choice",
    prompt: "Which anatomical structure represents the primary functional site of gas exchange in the human respiratory system?",
    options: ["Alveoli", "Trachea", "Epiglottis", "Larynx"],
    correctAnswer: "Alveoli",
    explanation: "Alveoli are surrounded by capillary networks that allow oxygen and carbon dioxide diffusion across the thin respiratory membrane.",
    difficulty: "Easy",
    tags: ["respiratory", "Alveoli", "A&P"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-5",
    subjectId: "anatomy-physiology",
    topicId: "cardiovascular-system",
    type: "Identification",
    prompt: "Identify the physiological term that describes the volume of blood delivered to tissues to supply oxygen and nutrients.",
    options: [],
    correctAnswer: "Perfusion",
    explanation: "Perfusion is the continuous passage of oxygenated blood through the circulatory system to body tissues and organs.",
    difficulty: "Easy",
    tags: ["cardiovascular", "Perfusion"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-ap-3",
    subjectId: "anatomy-physiology",
    topicId: "cardiovascular-system",
    type: "Multiple Choice",
    prompt: "Which specialized cardiac tissue serves as the primary electrical pacemaker of the normal human heart?",
    options: [
      "Sinoatrial (SA) Node",
      "Atrioventricular (AV) Node",
      "Bundle of His",
      "Purkinje Fibers",
    ],
    correctAnswer: "Sinoatrial (SA) Node",
    explanation: "The SA node in the right atrium initiates normal sinus rhythm at 60–100 bpm.",
    difficulty: "Easy",
    tags: ["Cardiac Conduction", "SA Node"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-ap-4",
    subjectId: "anatomy-physiology",
    topicId: "cardiovascular-system",
    type: "True/False",
    prompt: "The pulmonary veins are unique blood vessels because they carry oxygen-rich (oxygenated) blood from the lungs into the left atrium of the heart.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Unlike systemic veins which carry deoxygenated blood, pulmonary veins transport freshly oxygenated blood from pulmonary capillaries back to the left heart.",
    difficulty: "Easy",
    tags: ["Pulmonary Circulation", "A&P"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-ap-5",
    subjectId: "anatomy-physiology",
    topicId: "renal-system",
    type: "Select All That Apply",
    prompt: "Which of the following are primary physiological functions performed by the healthy human kidney? Select all that apply.",
    options: [
      "Regulation of fluid balance and blood pressure via the RAAS pathway",
      "Excretion of metabolic waste products like urea and creatinine",
      "Secretion of erythropoietin to stimulate red blood cell production",
      "Activation of Vitamin D (calcitriol) for calcium absorption",
      "Production of bile for fat emulsification",
    ],
    correctAnswer: [
      "Regulation of fluid balance and blood pressure via the RAAS pathway",
      "Excretion of metabolic waste products like urea and creatinine",
      "Secretion of erythropoietin to stimulate red blood cell production",
      "Activation of Vitamin D (calcitriol) for calcium absorption",
    ],
    explanation: "Bile is synthesized by the liver, not the kidneys. All other listed functions are essential renal operations.",
    difficulty: "Medium",
    tags: ["Renal Physiology", "Kidney Functions"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-ap-6",
    subjectId: "anatomy-physiology",
    topicId: "nervous-system",
    type: "Identification",
    prompt: "Identify the cranial nerve (Cranial Nerve X) that provides parasympathetic innervation to the heart, lungs, and gastrointestinal tract.",
    options: [],
    correctAnswer: "Vagus Nerve",
    explanation: "The Vagus Nerve (CN X) is the longest cranial nerve, responsible for parasympathetic heart rate regulation and gut motility.",
    difficulty: "Medium",
    tags: ["Cranial Nerves", "Vagus Nerve", "Neuro"],
    source: "OpenStax Anatomy and Physiology 2e",
  },
  {
    id: "q-ap-7",
    subjectId: "anatomy-physiology",
    topicId: "renal-system",
    type: "Patient Scenario",
    scenario: {
      patient: "A 58-year-old with chronic kidney disease (CKD Stage 5) is admitted for missed dialysis sessions.",
      vitals: ["BP: 168/98 mmHg", "Pulse: 48 bpm (irregular)", "RR: 22/min", "Temp: 36.9°C"],
      assessment: "Lab results reveal Serum Potassium: 7.1 mEq/L (Critical high). Telemetry monitor displays tall, peaked T-waves, widened QRS complex, and prolonged PR interval.",
    },
    prompt: "What life-threatening physiological complication is this patient at highest immediate risk for?",
    options: [
      "Lethal cardiac dysrhythmias (ventricular fibrillation or asystole)",
      "Acute hypovolemic shock",
      "Respiratory alkalosis with hyperventilation",
      "Severe hypoglycemia",
    ],
    correctAnswer: "Lethal cardiac dysrhythmias (ventricular fibrillation or asystole)",
    explanation: "Severe hyperkalemia (K+ > 6.5 mEq/L) alters myocardial cell membrane resting potential, producing characteristic ECG changes and placing the patient at imminent risk for fatal ventricular arrhythmias.",
    difficulty: "Hard",
    tags: ["Hyperkalemia", "ECG", "Renal", "Electrolytes"],
    source: "Open RN Health Alterations & A&P",
  },

  // ==========================================
  // SUBJECT 4: Pharmacology
  // ==========================================
  {
    id: "q-6",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    type: "Multiple Choice",
    prompt: "A medication label does not match the medication administration record. What should the nurse do first?",
    options: [
      "Pause and verify the order and medication before administration",
      "Administer it because the patient is waiting",
      "Ask a family member if it looks familiar",
      "Document the medication as refused",
    ],
    correctAnswer: "Pause and verify the order and medication before administration",
    explanation: "Medication discrepancies must always be halted and verified prior to giving any dose.",
    difficulty: "Medium",
    tags: ["medication safety", "10 Rights"],
    source: "Open RN Nursing Pharmacology (2nd ed. NCBI NBK595000)",
  },
  {
    id: "q-7",
    subjectId: "pharmacology",
    topicId: "dosage-calculations",
    type: "True/False",
    prompt: "When unsure about a dosage calculation, it is safer to recheck and seek independent verification before giving the medication.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Independent double checks and dose verification prevent medication calculation errors.",
    difficulty: "Easy",
    tags: ["dosage"],
    source: "Open RN Nursing Pharmacology",
  },
  {
    id: "q-p-3",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    type: "Multiple Choice",
    prompt: "Which medication serves as the specific competitive antagonist and antidote for acute Opioid overdose?",
    options: ["Naloxone (Narcan)", "Protamine Sulfate", "Flumazenil", "Vitamin K (Phytonadione)"],
    correctAnswer: "Naloxone (Narcan)",
    explanation: "Naloxone rapidly reverses central nervous system and respiratory depression caused by opioids.",
    difficulty: "Easy",
    tags: ["Naloxone", "Opioids", "Antidotes"],
    source: "Open RN Nursing Pharmacology (2nd ed.)",
  },
  {
    id: "q-p-4",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    type: "Select All That Apply",
    prompt: "Which medications are classified as High-Alert Medications (PINCH acronym) requiring heightened verification and caution? Select all that apply.",
    options: [
      "Potassium chloride IV concentrate",
      "Insulin subcutaneous and IV",
      "Narcotics and Opioids",
      "Chemotherapy antineoplastic agents",
      "Heparin and systemic anticoagulants",
    ],
    correctAnswer: [
      "Potassium chloride IV concentrate",
      "Insulin subcutaneous and IV",
      "Narcotics and Opioids",
      "Chemotherapy antineoplastic agents",
      "Heparin and systemic anticoagulants",
    ],
    explanation: "PINCH represents Potassium, Insulin, Narcotics, Chemotherapy, and Heparin — drugs bearing the highest risk of causing significant patient harm if misused.",
    difficulty: "Medium",
    tags: ["High-Alert", "PINCH", "Med Safety"],
    source: "ISMP & Open RN Nursing Pharmacology",
  },
  {
    id: "q-p-5",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    type: "Identification",
    prompt: "Identify the specific antidote administered to neutralize unfractionated Heparin in cases of severe hemorrhage.",
    options: [],
    correctAnswer: "Protamine Sulfate",
    explanation: "Protamine sulfate is a strongly basic protein that binds heparin to form an inactive salt complex.",
    difficulty: "Medium",
    tags: ["Heparin", "Protamine Sulfate", "Antidotes"],
    source: "Open RN Nursing Pharmacology",
  },
  {
    id: "q-p-6",
    subjectId: "pharmacology",
    topicId: "drug-classifications",
    type: "Prioritization",
    prompt: "A nurse is preparing to administer scheduled morning Metoprolol (Lopressor) 50 mg PO to a hospitalized patient. Vital signs are: BP 94/58 mmHg, Apical Pulse 50 bpm. What is the nurse's priority action?",
    options: [
      "Hold the Metoprolol dose, re-check vital signs, and notify the prescribing healthcare provider",
      "Administer the medication with a full glass of water as ordered",
      "Double the dose to stimulate beta-1 receptors",
      "Administer IV push atropine without an order",
    ],
    correctAnswer: "Hold the Metoprolol dose, re-check vital signs, and notify the prescribing healthcare provider",
    explanation: "Beta-blockers like Metoprolol should generally be withheld if apical heart rate is < 60 bpm or systolic BP is < 100 mmHg.",
    difficulty: "Medium",
    tags: ["Beta-Blockers", "Metoprolol", "Prioritization"],
    source: "Open RN Nursing Pharmacology",
  },
  {
    id: "q-p-7",
    subjectId: "pharmacology",
    topicId: "medication-safety",
    type: "Patient Scenario",
    scenario: {
      patient: "A 70-year-old taking Digoxin 0.25 mg PO daily for chronic heart failure arrives at the clinic with blurred vision, yellow-green visual halos, loss of appetite, and nausea.",
      vitals: ["Apical Pulse: 44 bpm (irregular)", "BP: 108/64 mmHg", "RR: 16/min"],
      assessment: "Serum Digoxin level is reported at 2.8 ng/mL (Therapeutic range: 0.5–2.0 ng/mL). Serum Potassium is 3.0 mEq/L (Hypokalemic).",
    },
    prompt: "Which clinical condition does the nurse recognize, and what is the underlying risk factor?",
    options: [
      "Digoxin toxicity exacerbated by hypokalemia",
      "Normal therapeutic medication response requiring no action",
      "Acute allergic anaphylaxis to cardiac glycosides",
      "Hypertensive crisis requiring sublingual nitrates",
    ],
    correctAnswer: "Digoxin toxicity exacerbated by hypokalemia",
    explanation: "Hypokalemia enhances digoxin binding to myocardial ATPase pumps, precipitating Digoxin Toxicity (visual halos, GI upset, severe bradycardia).",
    difficulty: "Hard",
    tags: ["Digoxin", "Toxicity", "Hypokalemia", "Cardiology"],
    source: "Open RN Nursing Pharmacology",
  },

  // ==========================================
  // SUBJECT 5: Medical-Surgical Nursing
  // ==========================================
  {
    id: "q-8",
    subjectId: "medical-surgical",
    topicId: "respiratory-care",
    type: "Patient Scenario",
    scenario: {
      patient: "A 68-year-old patient reports shortness of breath after walking to the bathroom.",
      vitals: ["RR 26/min", "SpO2 91% on room air", "Pulse 104/min"],
      assessment: "The patient is sitting forward and speaking in short phrases.",
    },
    prompt: "Which nursing action is the best immediate priority?",
    options: [
      "Assist the patient into a more upright (High Fowler's) position and continue focused respiratory assessment",
      "Leave the room to document the finding",
      "Offer a full meal tray",
      "Delay assessment until the next scheduled vital signs",
    ],
    correctAnswer: "Assist the patient into a more upright (High Fowler's) position and continue focused respiratory assessment",
    explanation: "Elevating the head of the bed enhances lung expansion and diaphragm excursion in acute dyspnea.",
    difficulty: "Medium",
    tags: ["respiratory", "priority", "positioning"],
    source: "Open RN Health Alterations (NCBI NBK613078)",
  },
  {
    id: "q-9",
    subjectId: "medical-surgical",
    topicId: "cardiac-care",
    type: "Select All That Apply",
    prompt: "Which assessment findings indicate systemic hypoperfusion in a med-surg patient? Select all that apply.",
    options: [
      "New acute confusion or lethargy",
      "Cool, clammy, and pale skin",
      "Oliguria / Low urine output (< 30 mL/hr)",
      "Bounding, full peripheral pulses (4+)",
      "Delayed capillary refill time (> 3 seconds)",
    ],
    correctAnswer: [
      "New acute confusion or lethargy",
      "Cool, clammy, and pale skin",
      "Oliguria / Low urine output (< 30 mL/hr)",
      "Delayed capillary refill time (> 3 seconds)",
    ],
    explanation: "Hypoperfusion manifests through altered cerebral perfusion (confusion), peripheral vasoconstriction (cool skin, delayed refill), and decreased renal blood flow (oliguria).",
    difficulty: "Medium",
    tags: ["perfusion", "shock", "cardiac"],
    source: "Open RN Health Alterations",
  },
  {
    id: "q-ms-3",
    subjectId: "medical-surgical",
    topicId: "cardiac-care",
    type: "Multiple Choice",
    prompt: "Which clinical manifestation is characteristic of Left-Sided Heart Failure rather than Right-Sided Heart Failure?",
    options: [
      "Bilateral pulmonary crackles and paroxysmal nocturnal dyspnea (PND)",
      "Jugular venous distention (JVD) at 45 degrees",
      "Pitting pedal edema of the lower extremities",
      "Ascites and hepatosplenomegaly",
    ],
    correctAnswer: "Bilateral pulmonary crackles and paroxysmal nocturnal dyspnea (PND)",
    explanation: "Left ventricular backward failure causes elevated pulmonary venous pressure and fluid extravasation into alveoli (crackles, dyspnea). Right ventricular failure causes systemic venous congestion.",
    difficulty: "Medium",
    tags: ["Heart Failure", "Left vs Right", "Med-Surg"],
    source: "Open RN Health Alterations",
  },
  {
    id: "q-ms-4",
    subjectId: "medical-surgical",
    topicId: "gastrointestinal-care",
    type: "Identification",
    prompt: "Identify the landmark anatomical point located one-third the distance between the anterior superior iliac spine and the umbilicus, classic for tenderness in acute appendicitis.",
    options: [],
    correctAnswer: "McBurney's Point",
    explanation: "McBurney's point tenderness is a hallmark clinical sign of acute appendiceal inflammation.",
    difficulty: "Medium",
    tags: ["Appendicitis", "McBurney", "GI"],
    source: "Open RN Health Alterations",
  },
  {
    id: "q-ms-5",
    subjectId: "medical-surgical",
    topicId: "endocrine-care",
    type: "Patient Scenario",
    scenario: {
      patient: "A 22-year-old with Type 1 Diabetes Mellitus is brought to the ED by roommates with deep, rapid respirations and drowsiness.",
      vitals: ["BP: 92/58 mmHg", "Pulse: 122 bpm", "RR: 32/min (Kussmaul breathing)", "Temp: 37.8°C"],
      assessment: "Patient's breath has a distinct fruity, acetone odor. Fingerstick Blood Glucose is 520 mg/dL. Arterial Blood Gas: pH 7.18, HCO3 12 mEq/L, PaCO2 28 mmHg (Metabolic Acidosis). Urine positive for heavy ketones.",
    },
    prompt: "Which acute complication is this patient experiencing, and what is the initial fluid resuscitation priority?",
    options: [
      "Diabetic Ketoacidosis (DKA); initiate rapid IV infusion of 0.9% Normal Saline",
      "Hyperosmolar Hyperglycemic State (HHS); administer subcutaneous glucagon",
      "Severe Hypoglycemia; push 50% Dextrose IV bolus immediately",
      "Respiratory Alkalosis; place patient on non-rebreather mask at 15 L/min",
    ],
    correctAnswer: "Diabetic Ketoacidosis (DKA); initiate rapid IV infusion of 0.9% Normal Saline",
    explanation: "DKA is characterized by hyperglycemia, ketosis, and metabolic acidosis with Kussmaul breathing. The immediate initial treatment priority is aggressive isotonic IV fluid resuscitation (0.9% NS) to restore intravascular volume before starting regular insulin infusion.",
    difficulty: "Hard",
    tags: ["DKA", "Diabetes", "Fluid Resuscitation", "Metabolic Acidosis"],
    source: "Open RN Health Alterations & Endocrine Guidelines",
  },

  // ==========================================
  // SUBJECT 6: Maternal and Child Nursing
  // ==========================================
  {
    id: "q-10",
    subjectId: "maternal-child",
    topicId: "newborn-care",
    type: "Multiple Choice",
    prompt: "Which nursing intervention is the most effective method to prevent heat loss through evaporation in a newly delivered neonate?",
    options: [
      "Thoroughly drying the infant with warm towels and placing skin-to-skin on the mother's chest",
      "Placing the newborn directly next to an open air conditioner",
      "Leaving wet delivery linens underneath the infant in the crib",
      "Delaying drying until after the first bath is completed",
    ],
    correctAnswer: "Thoroughly drying the infant with warm towels and placing skin-to-skin on the mother's chest",
    explanation: "Drying removes amniotic fluid to eliminate evaporative heat loss, and skin-to-skin contact provides conductive warmth.",
    difficulty: "Easy",
    tags: ["newborn", "thermoregulation"],
    source: "Open RN Nursing Health Promotion (NCBI NBK615319)",
  },
  {
    id: "q-mc-2",
    subjectId: "maternal-child",
    topicId: "prenatal-care",
    type: "Multiple Choice",
    prompt: "A pregnant client's Last Menstrual Period (LMP) began on June 10, 2026. Using Naegele's Rule, what is her Estimated Date of Delivery (EDD)?",
    options: [
      "March 17, 2027",
      "March 10, 2027",
      "April 17, 2027",
      "February 17, 2027",
    ],
    correctAnswer: "March 17, 2027",
    explanation: "Naegele's Rule: Subtract 3 months (March), Add 7 days (17), Add 1 year (2027) = March 17, 2027.",
    difficulty: "Medium",
    tags: ["Naegele's Rule", "EDD", "Obstetrics"],
    source: "Open RN Nursing Health Promotion",
  },
  {
    id: "q-mc-3",
    subjectId: "maternal-child",
    topicId: "postpartum-care",
    type: "True/False",
    prompt: "A distended urinary bladder in a postpartum patient can displace the uterine fundus upwards and to the right, causing uterine atony and increasing the risk of postpartum hemorrhage.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Full bladder displacement prevents the myometrium from contracting firmly down on open placental site vessels, leading to boggy uterus and hemorrhage.",
    difficulty: "Easy",
    tags: ["Postpartum Hemorrhage", "Fundus", "Bladder"],
    source: "Open RN Nursing Health Promotion",
  },
  {
    id: "q-mc-4",
    subjectId: "maternal-child",
    topicId: "labor-delivery",
    type: "Select All That Apply",
    prompt: "Which clinical characteristics distinguish True Labor from False Labor (Braxton Hicks contractions)? Select all that apply.",
    options: [
      "Contractions become progressively regular, longer, and stronger",
      "Progressive cervical dilation and effacement occur",
      "Pain often begins in the lower back and radiates around to the abdomen",
      "Walking intensifies true labor contractions rather than relieving them",
      "Contractions completely cease after drinking water or resting",
    ],
    correctAnswer: [
      "Contractions become progressively regular, longer, and stronger",
      "Progressive cervical dilation and effacement occur",
      "Pain often begins in the lower back and radiates around to the abdomen",
      "Walking intensifies true labor contractions rather than relieving them",
    ],
    explanation: "True labor produces cervical change and intensifies with activity; false contractions are irregular, lack cervical change, and diminish with rest or hydration.",
    difficulty: "Medium",
    tags: ["Labor", "True vs False Labor"],
    source: "Open RN Nursing Health Promotion",
  },
  {
    id: "q-mc-5",
    subjectId: "maternal-child",
    topicId: "newborn-care",
    type: "Identification",
    prompt: "Identify the normal physiological newborn phenomenon where the infant's trunk and mucosa are pink, but the hands and feet appear cyanotic/blue during the first 24–48 hours of life.",
    options: [],
    correctAnswer: "Acrocyanosis",
    explanation: "Acrocyanosis is a benign finding in neonates caused by immature peripheral circulation and vasomotor instability.",
    difficulty: "Medium",
    tags: ["Acrocyanosis", "Newborn Assessment"],
    source: "Open RN Nursing Health Promotion",
  },
  {
    id: "q-mc-6",
    subjectId: "maternal-child",
    topicId: "postpartum-care",
    type: "Prioritization",
    prompt: "A nurse assesses a client 2 hours post-vaginal delivery and notes a completely soaked perineal pad within 15 minutes, with large clots. The uterine fundus is palpated as soft and boggy above the umbilicus. What is the immediate first nursing action?",
    options: [
      "Perform vigorous fundal massage until the uterus becomes firm",
      "Administer IV antibiotics as ordered",
      "Leave the room to obtain a new perineal pad",
      "Place the patient in prone position",
    ],
    correctAnswer: "Perform vigorous fundal massage until the uterus becomes firm",
    explanation: "Fundal massage stimulates uterine myometrial contractions to compress blood vessels and control postpartum hemorrhage.",
    difficulty: "Hard",
    tags: ["Postpartum Hemorrhage", "Fundal Massage", "Priority"],
    source: "Open RN Nursing Health Promotion",
  },
  {
    id: "q-mc-7",
    subjectId: "maternal-child",
    topicId: "newborn-care",
    type: "Patient Scenario",
    scenario: {
      patient: "A full-term infant is assessed at 1 minute post-delivery.",
      vitals: ["Heart Rate: 130 bpm", "Vigorous, loud crying with regular breathing"],
      assessment: "Active spontaneous movement of all extremities; vigorous cough and sneeze elicited with bulb suctioning; body trunk is pink, but hands and feet are bluish (acrocyanosis).",
    },
    prompt: "What is this newborn's calculated APGAR score at 1 minute?",
    options: ["9", "10", "8", "7"],
    correctAnswer: "9",
    explanation: "APGAR calculation: Heart rate >100 (+2), Strong cry (+2), Active movement (+2), Reflex response (+2), Color body pink with blue hands/feet acrocyanosis (+1) = 9/10.",
    difficulty: "Medium",
    tags: ["APGAR Scoring", "Newborn", "Pediatrics"],
    source: "Open RN Nursing Health Promotion",
  },

  // ==========================================
  // SUBJECT 7: Psychiatric Nursing
  // ==========================================
  {
    id: "q-11",
    subjectId: "psychiatric",
    topicId: "therapeutic-communication",
    type: "Multiple Choice",
    prompt: "Which nurse response best demonstrates therapeutic communication when talking to a client who feels overwhelmed?",
    options: [
      "Tell me more about what that has been like for you.",
      "You should not feel that way, things will get better.",
      "Everything happens for a reason, so do not worry.",
      "I know exactly how you feel because I had a hard week too.",
    ],
    correctAnswer: "Tell me more about what that has been like for you.",
    explanation: "Open-ended exploration invites the client to elaborate on their feelings without judgment or deflection.",
    difficulty: "Easy",
    tags: ["communication", "Therapeutic"],
    source: "Open RN Mental Health and Community Concepts (NCBI NBK616982)",
  },
  {
    id: "q-12",
    subjectId: "psychiatric",
    topicId: "crisis-intervention",
    type: "Prioritization",
    prompt: "A patient is escalating verbally and aggressively pacing in a crowded dayroom. Which priority principle must guide the nurse's first action?",
    options: [
      "Ensuring immediate safety for the patient, other clients, and staff",
      "Providing detailed psychoeducation on anger management",
      "Completing discharge paperwork",
      "Demanding the client sign a behavioral contract immediately",
    ],
    correctAnswer: "Ensuring immediate safety for the patient, other clients, and staff",
    explanation: "In any behavioral escalation or crisis, safety and de-escalation take precedence over education or administrative tasks.",
    difficulty: "Medium",
    tags: ["crisis", "priority", "safety"],
    source: "Open RN Mental Health and Community Concepts",
  },
  {
    id: "q-psy-3",
    subjectId: "psychiatric",
    topicId: "psychopharmacology",
    type: "Multiple Choice",
    prompt: "What is the recommended therapeutic serum Lithium level range for maintenance therapy in a client with Bipolar Disorder?",
    options: [
      "0.6 to 1.2 mEq/L",
      "2.0 to 3.5 mEq/L",
      "0.1 to 0.4 mEq/L",
      "4.0 to 6.0 mEq/L",
    ],
    correctAnswer: "0.6 to 1.2 mEq/L",
    explanation: "Lithium has a narrow therapeutic index (0.6–1.2 mEq/L). Levels above 1.5 mEq/L can cause toxicity (tremors, ataxia, vomiting, seizures).",
    difficulty: "Medium",
    tags: ["Lithium", "Therapeutic Range", "Bipolar"],
    source: "Open RN Mental Health and Community Concepts",
  },
  {
    id: "q-psy-4",
    subjectId: "psychiatric",
    topicId: "crisis-intervention",
    type: "True/False",
    prompt: "When a psychotic client states 'The radio is speaking directly to me and telling me what to do', the nurse should agree with the delusion to avoid triggering agitation.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "The nurse must never reinforce or validate delusions/hallucinations. Instead, gently present reality and focus on the client's feelings (e.g., 'That sounds frightening, but I do not hear the radio speaking').",
    difficulty: "Easy",
    tags: ["Psychosis", "Hallucinations", "Reality Testing"],
    source: "Open RN Mental Health and Community Concepts",
  },
  {
    id: "q-psy-5",
    subjectId: "psychiatric",
    topicId: "therapeutic-communication",
    type: "Select All That Apply",
    prompt: "Which communication patterns are Non-Therapeutic communication barriers that nurses must avoid? Select all that apply.",
    options: [
      "Offering false reassurance (e.g. 'Don't worry, everything will be fine')",
      "Asking probing 'Why' questions (e.g. 'Why did you make that choice?')",
      "Giving unsolicited personal advice (e.g. 'If I were you, I would leave')",
      "Belittling expressed feelings (e.g. 'Everyone gets depressed sometimes')",
      "Using therapeutic silence to allow the client time to reflect",
    ],
    correctAnswer: [
      "Offering false reassurance (e.g. 'Don't worry, everything will be fine')",
      "Asking probing 'Why' questions (e.g. 'Why did you make that choice?')",
      "Giving unsolicited personal advice (e.g. 'If I were you, I would leave')",
      "Belittling expressed feelings (e.g. 'Everyone gets depressed sometimes')",
    ],
    explanation: "Silence is an active therapeutic communication tool. The other four choices block authentic client dialogue and increase defensiveness.",
    difficulty: "Medium",
    tags: ["Non-Therapeutic", "Communication Barriers"],
    source: "Open RN Mental Health and Community Concepts",
  },
  {
    id: "q-psy-6",
    subjectId: "psychiatric",
    topicId: "psychopharmacology",
    type: "Identification",
    prompt: "Identify the potentially fatal syndrome caused by combining multiple serotonergic medications, characterized by hyperreflexia, clonus, fever, agitation, and diaphoresis.",
    options: [],
    correctAnswer: "Serotonin Syndrome",
    explanation: "Serotonin Syndrome is a life-threatening toxicity caused by excessive serotonin accumulation, requiring immediate discontinuation of serotonergic drugs and supportive care.",
    difficulty: "Medium",
    tags: ["Serotonin Syndrome", "SSRIs", "Psychopharm"],
    source: "Open RN Mental Health and Community Concepts",
  },
  {
    id: "q-psy-7",
    subjectId: "psychiatric",
    topicId: "anxiety",
    type: "Patient Scenario",
    scenario: {
      patient: "A 30-year-old client admitted to the psychiatric unit with acute Bipolar I Mania is constantly pacing the hallway, talking at rapid pressure-speech, and refuses to sit down for tray meals.",
      vitals: ["Pulse: 106 bpm", "BP: 128/82 mmHg", "Temp: 37.1°C"],
      assessment: "Client has lost 3 kg over the past week due to hyperactivity and hypermetabolism. Attention span is very short, and client intrudes into group activities.",
    },
    prompt: "Which nutritional nursing intervention is most appropriate to meet this client's high caloric demands?",
    options: [
      "Provide frequent high-protein, high-calorie finger foods and portable snacks that can be consumed while walking",
      "Confine the client to the dining room until the entire meal tray is finished",
      "Insert an indwelling nasogastric feeding tube immediately",
      "Offer only black coffee and diet soda throughout the day",
    ],
    correctAnswer: "Provide frequent high-protein, high-calorie finger foods and portable snacks that can be consumed while walking",
    explanation: "Manic clients have extreme energy expenditure and cannot tolerate sitting through traditional meals. Portable finger foods (sandwiches, cheese sticks, protein smoothies) maintain nutrition without force.",
    difficulty: "Medium",
    tags: ["Bipolar Mania", "Nutrition", "Finger Foods"],
    source: "Open RN Mental Health and Community Concepts",
  },
];

export function getSubject(subjectId: string) {
  return subjects.find((subject) => subject.id === subjectId);
}

export function getTopic(subjectId: string, topicId: string) {
  return getSubject(subjectId)?.topics.find((topic) => topic.id === topicId);
}

export function getTopicName(subjectId: string, topicId: string) {
  return getTopic(subjectId, topicId)?.name ?? "General";
}

export function getSubjectName(subjectId: string) {
  return getSubject(subjectId)?.name ?? "Nursing";
}

export function weakTopics() {
  return subjects
    .flatMap((subject) =>
      subject.topics.map((topic) => ({
        ...topic,
        subjectId: subject.id,
        subjectName: subject.name,
      })),
    )
    .sort((a, b) => a.mastery - b.mastery)
    .slice(0, 5);
}
